import type { PracticalTaskDef } from "../task-schema";
import { makeBlockReflection, makePractical } from "./shared";

export const BLOCK_06_TASKS: PracticalTaskDef[] = [
  makePractical({
    blockId: 6,
    taskNumber: 3,
    evidenceRef: "Block_6_Task_3_Electrical_Diagnostic_Check",
    title: "Electrical Diagnostic Testing and Evidence Recording",
    scenario:
      "A vehicle has an electrical concern requiring structured testing. You must carry out safe electrical checks, record values and explain whether the evidence confirms the fault or requires further diagnosis.",
    objectives: [
      "Follow a structured electrical testing process.",
      "Carry out voltage, continuity and resistance checks safely.",
      "Record and compare results to expected values.",
      "Explain findings using evidence, not assumption.",
      "Complete diagnostic documentation accurately.",
    ],
    estimatedMinutes: 60,
    sourcePdf: "Block_6_Task_3_Electrical_Diagnostic_Check_v1.0.pdf",
    weeks: "Weeks 51-60",
    dutiesCovered: "1-10",
    ksbsCovered: "K12-K19, S8-S15, B1, B2",
    materials: [
      "Light vehicle with an electrical concern",
      "Multimeter and suitable test leads",
      "Wiring diagram / technical data",
      "PPE and Apprentice Assessment Record",
    ],
    instructions: [
      "Follow a logical electrical testing sequence.",
      "Carry out voltage, continuity and resistance checks safely.",
      "Record actual values and compare with expected results.",
      "Explain whether the evidence confirms the fault or needs further diagnosis.",
      "Complete diagnostic documentation accurately.",
    ],
    measurementFields: [
      { key: "batteryVoltage", type: "text", label: "Battery voltage" },
      { key: "testPointVoltage", type: "text", label: "Test point voltage" },
      { key: "voltageDrop", type: "text", label: "Voltage drop" },
      { key: "continuity", type: "text", label: "Continuity result" },
      { key: "resistance", type: "text", label: "Resistance reading" },
      { key: "fuseRelay", type: "text", label: "Fuse/relay checked" },
      { key: "dtcs", type: "text", label: "Relevant DTCs" },
      {
        key: "confirmedFault",
        type: "text",
        label: "Confirmed fault/evidence",
      },
    ],
    knowledgeQuestions: [
      "Why should testing follow a logical sequence?",
      "What multimeter safety precautions apply?",
      "What can excessive voltage drop indicate?",
      "Why record actual values not just pass/fail?",
      "How do you avoid damaging a circuit?",
      "When should you use a wiring diagram/technical data?",
      "What further action is needed if the test does not confirm the fault?",
    ],
  }),
  makePractical({
    blockId: 6,
    taskNumber: 4,
    evidenceRef: "Block_6_Task_4_Air_Conditioning_Climate_Check",
    title: "Air Conditioning and Climate-Control Checks",
    scenario:
      "A customer reports poor cabin cooling or demisting. You must complete non-invasive air-conditioning/climate-control checks, record visible findings and identify when F-gas or specialist referral is required.",
    objectives: [
      "Inspect visible AC/climate components safely.",
      "Carry out non-invasive function checks within competence.",
      "Record refrigerant information without handling refrigerant.",
      "Identify likely causes and referral points.",
      "Explain customer recommendations.",
    ],
    estimatedMinutes: 60,
    sourcePdf: "Block_6_Task_4_Air_Conditioning_Climate_Check_v1.0.pdf",
    weeks: "Weeks 51-60",
    dutiesCovered: "1-10",
    ksbsCovered: "K12-K19, S8-S15, B1, B2",
    materials: [
      "Light vehicle with climate-control system",
      "Manufacturer AC information",
      "PPE and thermometer/vent temperature tool if available",
      "Apprentice Assessment Record",
    ],
    instructions: [
      "Inspect visible AC/climate components safely.",
      "Complete non-invasive function checks within competence.",
      "Record refrigerant information without handling refrigerant.",
      "Identify likely causes and when specialist referral is required.",
      "Explain customer recommendations clearly.",
    ],
    measurementFields: [
      { key: "refrigerantType", type: "text", label: "Refrigerant type" },
      {
        key: "refrigerantQty",
        type: "text",
        label: "Refrigerant quantity",
      },
      { key: "ventTemp", type: "text", label: "Vent temperature" },
      { key: "blower", type: "text", label: "Blower operation" },
      {
        key: "compressor",
        type: "text",
        label: "Compressor engagement",
      },
      {
        key: "visibleLeak",
        type: "text",
        label: "Visible leak/damage",
      },
      {
        key: "cabinFilter",
        type: "text",
        label: "Cabin filter condition",
      },
      {
        key: "referralRequired",
        type: "text",
        label: "Referral required yes/no",
      },
    ],
    knowledgeQuestions: [
      "Why is refrigerant handling only for qualified personnel?",
      "What visible checks are safe at Level 2?",
      "What customer symptoms indicate an AC concern?",
      "Why is cabin airflow important for demisting?",
      "What should you record if specialist referral is needed?",
      "What environmental responsibilities apply in AC work?",
      "How would you explain the limitations of the check to a customer?",
    ],
  }),
  makeBlockReflection(6),
];
