import type { PracticalTaskDef } from "../task-schema";
import {
  makeBlockReflection,
  makeJobCard,
  makeKnowledgeTest,
  makePractical,
} from "./shared";

export const BLOCK_08_TASKS: PracticalTaskDef[] = [
  makeKnowledgeTest(8),
  makeJobCard(8),
  makePractical({
    blockId: 8,
    taskNumber: 3,
    evidenceRef: "Block_8_Task_3_ABS_Wheel_Speed_Diagnostic",
    title: "ABS Wheel Speed Sensor Diagnostic Investigation",
    scenario:
      "A vehicle has an ABS or traction warning lamp. You must carry out a structured inspection and test of the wheel speed sensor circuit or output, record evidence and explain the likely fault or referral route.",
    objectives: [
      "Carry out safe ABS diagnostic checks.",
      "Identify ABS sensor type and related components.",
      "Record DTCs, signal outputs and visual findings.",
      "Explain how evidence supports the diagnosis.",
      "Identify effects on related systems and customer communication needs.",
    ],
    estimatedMinutes: 60,
    sourcePdf: "Block_8_Task_3_ABS_Wheel_Speed_Diagnostic_v1.0.pdf",
    weeks: "Weeks 71-80",
    dutiesCovered: "1-10",
    ksbsCovered: "K15-K21, S10-S15, B1, B2",
    materials: [
      "Light vehicle with ABS/traction warning",
      "Scan tool and suitable meter or scope if available",
      "Technical data for sensor type/output",
      "PPE and Apprentice Assessment Record",
    ],
    instructions: [
      "Carry out safe ABS diagnostic checks.",
      "Identify ABS sensor type and related components.",
      "Record DTCs, signal outputs and visual findings.",
      "Explain how the evidence supports the diagnosis.",
      "Identify effects on related systems and communicate next steps.",
    ],
    measurementFields: [
      { key: "dtcCode", type: "text", label: "DTC code" },
      { key: "sensorType", type: "text", label: "Sensor type" },
      {
        key: "expectedOutput",
        type: "text",
        label: "Expected waveform/output",
      },
      { key: "measuredOutput", type: "text", label: "Measured output" },
      {
        key: "airGap",
        type: "text",
        label: "Air gap if relevant",
      },
      { key: "wiringCondition", type: "text", label: "Wiring condition" },
      {
        key: "toneRing",
        type: "text",
        label: "Tone ring condition",
      },
      {
        key: "relatedSystems",
        type: "text",
        label: "Related systems affected",
      },
    ],
    knowledgeQuestions: [
      "What is the purpose of an ABS wheel speed sensor?",
      "What does air gap mean?",
      "What can cause an illuminated ABS lamp?",
      "Why can ABS faults affect other systems?",
      "Why may an oscilloscope beat a basic meter?",
      "How would you explain an ABS fault to a customer?",
      "What further tests or authorisation may be required?",
    ],
  }),
  makePractical({
    blockId: 8,
    taskNumber: 4,
    evidenceRef: "Block_8_Task_4_Tyre_Wear_Root_Cause",
    title: "Tyre Wear Root-Cause and Geometry Investigation",
    scenario:
      "A vehicle has excessive or uneven tyre wear. You must inspect the tyres and related steering/suspension geometry, record evidence and identify the likely root cause before recommending work.",
    objectives: [
      "Inspect tyre wear patterns and related components.",
      "Record geometry/alignment measurements where available.",
      "Identify likely root causes using evidence.",
      "Prioritise repairs, adjustment or referral.",
      "Explain the customer benefit of correct geometry.",
    ],
    estimatedMinutes: 60,
    sourcePdf: "Block_8_Task_4_Tyre_Wear_Root_Cause_v1.0.pdf",
    weeks: "Weeks 71-80",
    dutiesCovered: "1-10",
    ksbsCovered: "K15-K21, S10-S15, B1, B2",
    materials: [
      "Light vehicle with uneven tyre wear",
      "Tread depth gauge and pressure gauge",
      "Alignment/geometry equipment if available",
      "PPE and Apprentice Assessment Record",
    ],
    instructions: [
      "Inspect tyre wear patterns and related components.",
      "Record geometry and alignment measurements where available.",
      "Identify the likely root cause using evidence.",
      "Prioritise repairs, adjustment or referral.",
      "Explain the customer benefit of correct geometry.",
    ],
    measurementFields: [
      { key: "wearPattern", type: "text", label: "Tyre wear pattern" },
      { key: "treadNsf", type: "text", label: "NS/F tread depth" },
      { key: "treadOsf", type: "text", label: "OS/F tread depth" },
      { key: "frontToeMeasured", type: "text", label: "Front toe measured" },
      {
        key: "frontToeSpec",
        type: "text",
        label: "Front toe specification",
      },
      { key: "camberMeasured", type: "text", label: "Camber measured" },
      { key: "tyrePressure", type: "text", label: "Tyre pressure" },
      {
        key: "rootCause",
        type: "text",
        label: "Suspected root cause",
      },
    ],
    knowledgeQuestions: [
      "What wear pattern is caused by incorrect toe?",
      "Why check suspension before alignment?",
      "How does tyre pressure affect wear?",
      "Why is rear alignment/thrust angle important?",
      "How would you explain the benefits of correct geometry?",
      "What evidence confirms root cause versus symptom?",
      "What recommendation should you make if a component is worn?",
    ],
  }),
  makeBlockReflection(8),
];
