import type { PracticalTaskDef } from "../task-schema";
import {
  makeBlockReflection,
  makeJobCard,
  makeKnowledgeTest,
  makePractical,
} from "./shared";

export const BLOCK_03_TASKS: PracticalTaskDef[] = [
  makeKnowledgeTest(3),
  makeJobCard(3),
  makePractical({
    blockId: 3,
    taskNumber: 3,
    evidenceRef: "Block_3_Task_3_Interim_Service_and_Documentation",
    title: "Interim Service, Inspection and Documentation",
    scenario:
      "A vehicle is booked for an interim service. You must follow the service schedule, identify required service items, complete the inspection documentation and record any additional work requiring customer authorisation.",
    objectives: [
      "Follow a routine service workflow safely.",
      "Identify service items using manufacturer or workshop information.",
      "Complete service and inspection documentation accurately.",
      "Record additional work and customer authorisation requirements.",
      "Maintain good housekeeping and environmental control during the task.",
    ],
    estimatedMinutes: 60,
    sourcePdf: "Block_3_Task_3_Interim_Service_and_Documentation_v1.0.pdf",
    weeks: "Weeks 21-30",
    dutiesCovered: "1, 2, 3, 4, 5, 6, 7, 8",
    ksbsCovered: "K8-K16, S6-S12, B1, B2",
    materials: [
      "Light vehicle booked for interim service",
      "Service schedule / manufacturer information",
      "Service parts and fluids as specified",
      "PPE, waste containers and housekeeping equipment",
      "Apprentice Assessment Record",
    ],
    instructions: [
      "Follow the service schedule and identify required service items.",
      "Complete the inspection documentation accurately.",
      "Record any additional work requiring customer authorisation.",
      "Control waste and maintain housekeeping throughout.",
      "Confirm the vehicle is ready for handover or further work.",
    ],
    measurementFields: [
      {
        key: "oilSpec",
        type: "text",
        label: "Engine oil specification",
      },
      { key: "oilCapacity", type: "text", label: "Oil capacity" },
      {
        key: "oilFilter",
        type: "text",
        label: "Oil filter part number",
      },
      {
        key: "airCabinFilter",
        type: "text",
        label: "Air/cabin filter part number",
      },
      {
        key: "brakeFluid",
        type: "text",
        label: "Brake fluid condition",
      },
      {
        key: "coolant",
        type: "text",
        label: "Coolant strength/level",
      },
      { key: "tyrePressures", type: "text", label: "Tyre pressures" },
      { key: "wheelTorque", type: "text", label: "Wheel torque setting" },
    ],
    knowledgeQuestions: [
      "Why must a service schedule be followed?",
      "What information is needed before ordering service parts?",
      "Why must additional work be authorised before starting?",
      "How should waste oil or filters be controlled?",
      "What makes a job card clear and audit ready?",
      "How would you prioritise advisory and urgent defects?",
      "What evidence should be uploaded after the service task?",
    ],
  }),
  makePractical({
    blockId: 3,
    taskNumber: 4,
    evidenceRef: "Block_3_Task_4_Environmental_Spill_and_Waste_Control",
    title: "Environmental Spill Response and Waste Control",
    scenario:
      "During routine workshop activity, a fluid spill and several waste items are identified. You must make the area safe, identify waste streams, record the incident and explain how environmental controls prevent harm.",
    objectives: [
      "Respond to a workshop spill using safe procedures.",
      "Identify appropriate waste streams and storage controls.",
      "Use PPE and signage/barriers where required.",
      "Complete an environmental or incident record.",
      "Explain how good housekeeping supports safety and compliance.",
    ],
    estimatedMinutes: 45,
    sourcePdf: "Block_3_Task_4_Environmental_Spill_and_Waste_Control_v1.0.pdf",
    weeks: "Weeks 21-30",
    dutiesCovered: "1, 2, 3, 4, 5, 6, 7, 8",
    ksbsCovered: "K8-K16, S6-S12, B1, B2",
    materials: [
      "Spill kit and absorbent materials",
      "PPE and barrier/signage equipment",
      "COSHH information / waste stream guidance",
      "Incident or environmental record form",
      "Apprentice Assessment Record",
    ],
    instructions: [
      "Make the spill area safe using PPE, barriers and signage as required.",
      "Identify the substance and select the correct waste stream.",
      "Use the spill kit and contain waste correctly.",
      "Complete an environmental or incident record.",
      "Explain how housekeeping supports safety and compliance.",
    ],
    measurementFields: [
      { key: "substance", type: "text", label: "Substance involved" },
      { key: "ppeSelected", type: "text", label: "PPE selected" },
      { key: "spillKit", type: "text", label: "Spill kit used" },
      { key: "wasteStream", type: "text", label: "Waste stream selected" },
      { key: "areaIsolated", type: "text", label: "Area isolated yes/no" },
      { key: "coshhRef", type: "text", label: "COSHH reference" },
      { key: "incidentRef", type: "text", label: "Incident reference" },
      { key: "correctiveAction", type: "text", label: "Corrective action" },
    ],
    knowledgeQuestions: [
      "Why must spills be dealt with immediately?",
      "What information can be found on a COSHH sheet?",
      "Why must different waste streams be segregated?",
      "What could happen if waste fluids are disposed of incorrectly?",
      "How should the incident be recorded?",
      "Who should be informed if the spill cannot be controlled?",
      "How does housekeeping affect customer and colleague safety?",
    ],
  }),
  makeBlockReflection(3),
];
