import type { PracticalTaskDef } from "../task-schema";
import { makeBlockReflection, makePractical } from "./shared";

export const BLOCK_01_TASKS: PracticalTaskDef[] = [
  makePractical({
    blockId: 1,
    taskNumber: 3,
    evidenceRef: "Block_1_Task_3_Vehicle_Safety_Inspection",
    title: "Vehicle Safety Inspection and Workshop Preparation",
    scenario:
      "A customer vehicle has arrived for an initial safety inspection. You must prepare the work area, use PPE correctly, complete a structured inspection and record any safety-related findings without carrying out repairs.",
    objectives: [
      "Prepare the vehicle and workstation safely before inspection.",
      "Carry out a basic safety inspection using a methodical routine.",
      "Identify visible defects and record recommendations clearly.",
      "Demonstrate correct PPE, housekeeping and documentation practice.",
      "Explain which findings would require customer authorisation before work.",
    ],
    estimatedMinutes: 60,
    sourcePdf: "Block_1_Task_3_Vehicle_Safety_Inspection_v1.0.pdf",
    weeks: "Weeks 1-10",
    dutiesCovered: "1, 2, 3, 4, 5, 6",
    ksbsCovered: "Foundation KSBs (shared)",
    materials: [
      "Light vehicle suitable for inspection",
      "PPE and workshop safety equipment",
      "Tyre tread depth gauge and pressure gauge",
      "Manufacturer or workshop inspection checklist",
      "Apprentice Assessment Record",
    ],
    instructions: [
      "Prepare the vehicle and workstation safely before inspection.",
      "Carry out a basic safety inspection using a methodical routine.",
      "Record visible defects and recommendations clearly.",
      "Demonstrate correct PPE, housekeeping and documentation practice.",
      "Explain which findings would require customer authorisation before work.",
    ],
    measurementFields: [
      { key: "treadNsf", type: "text", label: "Tyre tread depth NS/F" },
      { key: "treadOsf", type: "text", label: "Tyre tread depth OS/F" },
      { key: "pressureNsf", type: "text", label: "Tyre pressure NS/F" },
      { key: "pressureOsf", type: "text", label: "Tyre pressure OS/F" },
      { key: "brakeFluid", type: "text", label: "Brake fluid condition" },
      { key: "batterySecurity", type: "text", label: "Battery security check" },
      { key: "lightsCheck", type: "text", label: "Lights/warning lamps check" },
      { key: "wheelTorque", type: "text", label: "Wheel torque setting" },
    ],
    knowledgeQuestions: [
      "Why must PPE be selected before starting the task?",
      "State the minimum legal tread depth for a car tyre.",
      "Why should defects be recorded clearly before speaking to the customer?",
      "What checks must be completed before raising a vehicle?",
      "Explain how poor housekeeping can create a workshop risk.",
      "Which defects would you class as safety critical?",
      "What further work or customer authorisation may be required?",
    ],
  }),
  makePractical({
    blockId: 1,
    taskNumber: 4,
    evidenceRef: "Block_1_Task_4_Basic_Braking_and_Tyre_Check",
    title: "Basic Brake and Tyre Condition Check",
    scenario:
      "A vehicle has been reported with possible tyre and brake wear during a basic workshop check. You must inspect visible brake and tyre components, record measurements and explain any customer recommendations.",
    objectives: [
      "Carry out brake and tyre checks using safe working practices.",
      "Measure tyre tread depth and inspect visible brake condition.",
      "Record findings, wheel torque and customer recommendations.",
      "Identify legal or safety concerns using evidence.",
      "Explain how tyre and brake condition affects vehicle safety.",
    ],
    estimatedMinutes: 60,
    sourcePdf: "Block_1_Task_4_Basic_Braking_and_Tyre_Check_v1.0.pdf",
    weeks: "Weeks 1-10",
    dutiesCovered: "1, 2, 3, 4, 5, 6",
    ksbsCovered: "Foundation KSBs (shared)",
    materials: [
      "Light vehicle suitable for brake and tyre checks",
      "Tread depth gauge and pressure gauge",
      "Torque wrench",
      "PPE and safe lifting equipment",
      "Apprentice Assessment Record",
    ],
    instructions: [
      "Inspect tyres and visible brake components using safe working practices.",
      "Measure tyre tread depth and record pressures.",
      "Record wheel torque and customer recommendations.",
      "Identify legal or safety concerns using evidence.",
      "Explain how tyre and brake condition affects vehicle safety.",
    ],
    measurementFields: [
      { key: "treadNsf", type: "text", label: "NS/F tread depth" },
      { key: "treadOsf", type: "text", label: "OS/F tread depth" },
      { key: "treadNsr", type: "text", label: "NS/R tread depth" },
      { key: "treadOsr", type: "text", label: "OS/R tread depth" },
      { key: "recPressure", type: "text", label: "Recommended tyre pressure" },
      { key: "measPressure", type: "text", label: "Measured tyre pressure" },
      { key: "wheelTorque", type: "text", label: "Wheel torque setting" },
      {
        key: "brakeCondition",
        type: "textarea",
        label: "Visible brake condition",
      },
    ],
    knowledgeQuestions: [
      "What are the legal tyre requirements for tread depth?",
      "Why must tyre pressures be checked before assessing wear?",
      "What brake defects may be identified during a visual inspection?",
      "What customer symptoms may indicate tyre or brake issues?",
      "Why is wheel torque important after wheel removal?",
      "How would you explain an advisory tyre defect to a customer?",
      "What documentation should be completed after the check?",
    ],
  }),
  makeBlockReflection(1),
];
