import type { PracticalTaskDef } from "../task-schema";
import { makeBlockReflection, makePractical } from "./shared";

export const BLOCK_07_TASKS: PracticalTaskDef[] = [
  makePractical({
    blockId: 7,
    taskNumber: 3,
    evidenceRef: "Block_7_Task_3_Steering_Component_Replacement",
    title: "Steering Component Replacement and Customer Recommendations",
    scenario:
      "A vehicle has steering play or a worn steering component. You must inspect the relevant area, remove/refit the component as instructed, record technical data and explain the customer recommendations.",
    objectives: [
      "Inspect steering components safely and accurately.",
      "Remove and refit a component as instructed.",
      "Record torque settings and component condition.",
      "Identify alignment implications and safety concerns.",
      "Explain the work and recommendations clearly.",
    ],
    estimatedMinutes: 60,
    sourcePdf: "Block_7_Task_3_Steering_Component_Replacement_v1.0.pdf",
    weeks: "Weeks 61-70",
    dutiesCovered: "1-10",
    ksbsCovered: "K14-K20, S10-S15, B1, B2",
    materials: [
      "Light vehicle with a steering concern",
      "Steering tools and torque wrench",
      "Manufacturer torque and alignment data",
      "PPE and safe lifting equipment",
      "Apprentice Assessment Record",
    ],
    instructions: [
      "Inspect the steering area safely and accurately.",
      "Remove and refit the component as instructed.",
      "Record torque settings and component condition.",
      "Identify alignment implications and safety concerns.",
      "Explain the work and customer recommendations clearly.",
    ],
    measurementFields: [
      { key: "steeringType", type: "text", label: "Steering system type" },
      {
        key: "componentReplaced",
        type: "text",
        label: "Component replaced",
      },
      {
        key: "trackRodTorque",
        type: "text",
        label: "Track rod nut torque",
      },
      { key: "wheelTorque", type: "text", label: "Wheel torque setting" },
      { key: "toeBefore", type: "text", label: "Toe setting before" },
      { key: "toeAfter", type: "text", label: "Toe setting after" },
      {
        key: "alignmentRequired",
        type: "text",
        label: "Alignment required yes/no",
      },
      {
        key: "postRepairCheck",
        type: "text",
        label: "Post-repair check result",
      },
    ],
    knowledgeQuestions: [
      "Why is steering condition safety critical?",
      "Why note the number of turns when removing a track rod end?",
      "What defects can be found on steering joints/racks?",
      "Why may alignment be needed after steering repairs?",
      "How can steering faults affect tyre wear?",
      "How would you explain the repair to a customer?",
      "What final checks are required before release?",
    ],
  }),
  makePractical({
    blockId: 7,
    taskNumber: 4,
    evidenceRef: "Block_7_Task_4_Engine_Management_Sensor_Check",
    title: "Engine Management Sensor Check and Handover",
    scenario:
      "A vehicle has an engine management concern. You must carry out a basic non-invasive sensor check using a scan tool or suitable method, record outputs and explain the evidence and next steps.",
    objectives: [
      "Identify relevant engine-management components.",
      "Use scan data or basic testing to check sensor operation.",
      "Record outputs and DTCs accurately.",
      "Explain findings in customer-friendly language.",
      "Recognise when further diagnosis or referral is needed.",
    ],
    estimatedMinutes: 60,
    sourcePdf: "Block_7_Task_4_Engine_Management_Sensor_Check_v1.0.pdf",
    weeks: "Weeks 61-70",
    dutiesCovered: "1-10",
    ksbsCovered: "K14-K20, S10-S15, B1, B2",
    materials: [
      "Light vehicle with an engine management concern",
      "Scan tool or suitable test method",
      "Technical data / expected sensor ranges",
      "PPE and Apprentice Assessment Record",
    ],
    instructions: [
      "Identify the relevant engine-management components.",
      "Use scan data or basic testing to check sensor operation.",
      "Record outputs and DTCs accurately.",
      "Explain findings in customer-friendly language.",
      "Identify when further diagnosis or referral is needed.",
    ],
    measurementFields: [
      { key: "componentChecked", type: "text", label: "Component checked" },
      { key: "dtcCode", type: "text", label: "DTC code" },
      { key: "liveData", type: "text", label: "Live data value" },
      {
        key: "expectedRange",
        type: "text",
        label: "Expected value/range",
      },
      {
        key: "connectorWiring",
        type: "text",
        label: "Connector/wiring condition",
      },
      { key: "sensorType", type: "text", label: "Sensor type" },
      { key: "toolUsed", type: "text", label: "Tool used" },
      { key: "nextStep", type: "text", label: "Confirmed next step" },
    ],
    knowledgeQuestions: [
      "Why should fault codes not be treated as automatic proof of a failed part?",
      "What is live data and how does it support diagnosis?",
      "Why avoid technical jargon in customer explanations?",
      "What checks should be done before replacing a sensor?",
      "How can engine management faults affect emissions?",
      "What evidence should be recorded on the job card?",
      "When should further diagnosis be authorised?",
    ],
  }),
  makeBlockReflection(7),
];
