import type { PracticalTaskDef } from "../task-schema";
import { makeBlockReflection, makePractical } from "./shared";

export const BLOCK_02_TASKS: PracticalTaskDef[] = [
  makePractical({
    blockId: 2,
    taskNumber: 3,
    evidenceRef: "Block_2_Task_3_Battery_and_Charging_Check",
    title: "Battery and Charging System Inspection",
    scenario:
      "A customer reports slow cranking and intermittent starting concerns. You must carry out basic battery and charging system checks, record results and explain whether further work is required.",
    objectives: [
      "Inspect battery condition and security safely.",
      "Take relevant electrical measurements using a multimeter or tester.",
      "Interpret basic battery and charging results.",
      "Record findings using clear documentation.",
      "Explain the next steps to the customer or assessor.",
    ],
    estimatedMinutes: 45,
    sourcePdf: "Block_2_Task_3_Battery_and_Charging_Check_v1.0.pdf",
    weeks: "Weeks 11-20",
    dutiesCovered: "1, 2, 3, 4, 5, 6",
    ksbsCovered: "K5-K14, S5-S10, B1, B2",
    materials: [
      "Light vehicle with 12V battery",
      "Multimeter or battery tester",
      "Manufacturer technical information",
      "PPE and battery handling equipment",
      "Apprentice Assessment Record",
    ],
    instructions: [
      "Prepare the vehicle and confirm the complaint with the assessor.",
      "Inspect battery security, terminals and visible condition.",
      "Measure battery voltage and charging voltage as instructed.",
      "Record results and compare with manufacturer or accepted values.",
      "Reinstate the vehicle and workstation to a pre-assessment condition.",
    ],
    measurementFields: [
      { key: "batteryVoltage", type: "text", label: "Battery voltage" },
      { key: "chargingVoltage", type: "text", label: "Charging voltage" },
      { key: "batteryRating", type: "text", label: "Battery rating" },
      {
        key: "terminalCondition",
        type: "text",
        label: "Battery terminal condition",
      },
      { key: "earthLead", type: "text", label: "Earth lead condition" },
      {
        key: "alternatorBelt",
        type: "text",
        label: "Alternator belt condition",
      },
      { key: "batterySecurity", type: "text", label: "Battery security" },
      { key: "dtcs", type: "text", label: "Relevant DTCs if checked" },
    ],
    knowledgeQuestions: [
      "Why is battery condition checked before replacing starting components?",
      "What safety precautions apply when working around batteries?",
      "What can low charging voltage indicate?",
      "Why should terminals and earth connections be inspected?",
      "How would you explain a weak battery result to a customer?",
      "What further checks may be required if the fault remains?",
      "What evidence should be recorded for the job card?",
    ],
  }),
  makePractical({
    blockId: 2,
    taskNumber: 4,
    evidenceRef: "Block_2_Task_4_TPMS_and_Tyre_Service",
    title: "TPMS, Tyre Pressure and Customer Documentation",
    scenario:
      "A vehicle has arrived with a tyre pressure warning lamp illuminated. You must inspect tyre condition and pressures, identify the TPMS type where possible, carry out a reset/relearn where appropriate and record customer-facing findings.",
    objectives: [
      "Inspect tyres and pressures safely and methodically.",
      "Identify direct or indirect TPMS operation where possible.",
      "Carry out or explain the correct reset/relearn procedure.",
      "Record technical data and customer advice clearly.",
      "Recognise when specialist TPMS diagnosis is required.",
    ],
    estimatedMinutes: 45,
    sourcePdf: "Block_2_Task_4_TPMS_and_Tyre_Service_v1.0.pdf",
    weeks: "Weeks 11-20",
    dutiesCovered: "1, 2, 3, 4, 5, 6",
    ksbsCovered: "K5-K14, S5-S10, B1, B2",
    materials: [
      "Light vehicle with TPMS",
      "Tyre pressure gauge",
      "TPMS reset/relearn tool or procedure information",
      "Torque wrench",
      "PPE and Apprentice Assessment Record",
    ],
    instructions: [
      "Confirm the TPMS warning and inspect tyre condition and pressures.",
      "Identify direct or indirect TPMS type where possible.",
      "Carry out or explain the correct reset/relearn procedure.",
      "Record technical data and customer advice clearly.",
      "Identify when specialist TPMS diagnosis is required.",
    ],
    measurementFields: [
      { key: "tpmsType", type: "text", label: "TPMS type" },
      { key: "pressureNsf", type: "text", label: "NS/F pressure" },
      { key: "pressureOsf", type: "text", label: "OS/F pressure" },
      { key: "pressureNsr", type: "text", label: "NS/R pressure" },
      { key: "pressureOsr", type: "text", label: "OS/R pressure" },
      {
        key: "recommendedPressure",
        type: "text",
        label: "Recommended pressure",
      },
      { key: "resetMethod", type: "text", label: "Reset/relearn method" },
      { key: "wheelTorque", type: "text", label: "Wheel torque setting" },
    ],
    knowledgeQuestions: [
      "What is the difference between direct and indirect TPMS?",
      "Why must tyre condition be checked before resetting TPMS?",
      "What faults can cause a TPMS warning lamp?",
      "What precautions are needed when working near TPMS valves?",
      "Why should wheel positions be recorded where relevant?",
      "How would you explain the TPMS warning to a customer?",
      "When should the task be referred for further diagnosis?",
    ],
  }),
  makeBlockReflection(2),
];
