/**
 * ADM14.0 Apprenticeship Evidence Pack checklist (From August 2022) v2.1.
 * Source form: ADM14.0_Apprenticeship_File_Checklist_v2.1
 * This is the canonical document list for the shared learner file pack page.
 */

export type Adm14RequirementKind = "mandatory" | "conditional";

export type Adm14RequirementDefinition = {
  reference: string;
  sectionKey: string;
  sectionTitle: string;
  originalBookletSection: string;
  requirementKind: Adm14RequirementKind;
  title: string;
  /** Form notes / applicability */
  applicability: string;
  isRecurring: boolean;
  /** Section 6 items typically apply once the apprenticeship has ended */
  endOfProgramme: boolean;
};

export const ADM14_FORM_CODE = "ADM14.0";
export const ADM14_FORM_TITLE =
  "Apprenticeship Evidence Pack Form (From August 2022)";

export const ADM14_REQUIREMENTS: Adm14RequirementDefinition[] = [
  // Section 1 — Programme Eligibility
  {
    reference: "1.1",
    sectionKey: "eligibility",
    sectionTitle: "Programme Eligibility",
    originalBookletSection: "Section 1",
    requirementKind: "mandatory",
    title: "Individual Learning Record (ILR)",
    applicability: "All programmes",
    isRecurring: false,
    endOfProgramme: false,
  },
  {
    reference: "1.2",
    sectionKey: "eligibility",
    sectionTitle: "Programme Eligibility",
    originalBookletSection: "Section 1",
    requirementKind: "mandatory",
    title: "Learner Enrolment Form",
    applicability: "All programmes",
    isRecurring: false,
    endOfProgramme: false,
  },
  {
    reference: "1.3",
    sectionKey: "eligibility",
    sectionTitle: "Programme Eligibility",
    originalBookletSection: "Section 1",
    requirementKind: "mandatory",
    title: "Learner Interview Form",
    applicability: "All programmes",
    isRecurring: false,
    endOfProgramme: false,
  },
  {
    reference: "1.4",
    sectionKey: "eligibility",
    sectionTitle: "Programme Eligibility",
    originalBookletSection: "Section 1",
    requirementKind: "mandatory",
    title: "Initial Assessment – BKSB Report",
    applicability: "All programmes",
    isRecurring: false,
    endOfProgramme: false,
  },
  {
    reference: "1.5",
    sectionKey: "eligibility",
    sectionTitle: "Programme Eligibility",
    originalBookletSection: "Section 1",
    requirementKind: "mandatory",
    title: "Initial Assessment – Knowledge, Skills and Behaviours Testing Record",
    applicability: "All programmes",
    isRecurring: false,
    endOfProgramme: false,
  },
  {
    reference: "1.6",
    sectionKey: "eligibility",
    sectionTitle: "Programme Eligibility",
    originalBookletSection: "Section 1",
    requirementKind: "mandatory",
    title: "Initial Assessment – PLR Report",
    applicability: "All programmes",
    isRecurring: false,
    endOfProgramme: false,
  },
  {
    reference: "1.7",
    sectionKey: "eligibility",
    sectionTitle: "Programme Eligibility",
    originalBookletSection: "Section 1",
    requirementKind: "conditional",
    title: "Initial Assessment – Additional Learning Support Assessment",
    applicability: "Where ALS is identified",
    isRecurring: false,
    endOfProgramme: false,
  },

  // Section 2 — Employer Enrolment
  {
    reference: "2.1",
    sectionKey: "employer",
    sectionTitle: "Employer Enrolment",
    originalBookletSection: "Section 2",
    requirementKind: "mandatory",
    title: "Employer Training Needs Analysis (TNA)",
    applicability: "All programmes",
    isRecurring: false,
    endOfProgramme: false,
  },
  {
    reference: "2.2",
    sectionKey: "employer",
    sectionTitle: "Employer Enrolment",
    originalBookletSection: "Section 2",
    requirementKind: "mandatory",
    title: "Employer Recruit an Apprentice Declaration",
    applicability: "All programmes",
    isRecurring: false,
    endOfProgramme: false,
  },
  {
    reference: "2.3",
    sectionKey: "employer",
    sectionTitle: "Employer Enrolment",
    originalBookletSection: "Section 2",
    requirementKind: "conditional",
    title: "Small Employer Waiver Evidence",
    applicability: "Where applicable",
    isRecurring: false,
    endOfProgramme: false,
  },
  {
    reference: "2.4",
    sectionKey: "employer",
    sectionTitle: "Employer Enrolment",
    originalBookletSection: "Section 2",
    requirementKind: "mandatory",
    title: "Employer Health and Safety Audit",
    applicability: "All programmes — tick each inspection when completed",
    isRecurring: true,
    endOfProgramme: false,
  },

  // Section 3 — App Agreement
  {
    reference: "3.1",
    sectionKey: "agreement",
    sectionTitle: "Apprenticeship Agreement",
    originalBookletSection: "Section 3",
    requirementKind: "mandatory",
    title: "Apprenticeship Agreement",
    applicability: "All programmes",
    isRecurring: false,
    endOfProgramme: false,
  },

  // Section 4 — Contract
  {
    reference: "4.1",
    sectionKey: "contract",
    sectionTitle: "Contract",
    originalBookletSection: "Section 4",
    requirementKind: "mandatory",
    title: "Training Plan",
    applicability: "All programmes",
    isRecurring: false,
    endOfProgramme: false,
  },
  {
    reference: "4.2",
    sectionKey: "contract",
    sectionTitle: "Contract",
    originalBookletSection: "Section 4",
    requirementKind: "mandatory",
    title: "Contract for Services (Training Agreement)",
    applicability: "All programmes",
    isRecurring: false,
    endOfProgramme: false,
  },

  // Section 5 — App Induction
  {
    reference: "5.1",
    sectionKey: "induction",
    sectionTitle: "Apprenticeship Induction",
    originalBookletSection: "Section 5",
    requirementKind: "mandatory",
    title: "Apprenticeship Induction Record",
    applicability: "All programmes",
    isRecurring: false,
    endOfProgramme: false,
  },

  // Section 6 — Apprenticeship Ended
  {
    reference: "6.1",
    sectionKey: "ended",
    sectionTitle: "Apprenticeship Ended",
    originalBookletSection: "Section 6",
    requirementKind: "mandatory",
    title: "Learner Completion Pack Record Form",
    applicability: "Once the apprenticeship has ended",
    isRecurring: false,
    endOfProgramme: true,
  },
  {
    reference: "6.2",
    sectionKey: "ended",
    sectionTitle: "Apprenticeship Ended",
    originalBookletSection: "Section 6",
    requirementKind: "mandatory",
    title: "Tri-Party agreement for End-Point Assessment",
    applicability: "Once the apprenticeship has ended / EPA pathway",
    isRecurring: false,
    endOfProgramme: true,
  },
  {
    reference: "6.3",
    sectionKey: "ended",
    sectionTitle: "Apprenticeship Ended",
    originalBookletSection: "Section 6",
    requirementKind: "mandatory",
    title: "Booking Confirmation Email with EPAO Evidence",
    applicability: "Once EPA is booked",
    isRecurring: false,
    endOfProgramme: true,
  },
  {
    reference: "6.4",
    sectionKey: "ended",
    sectionTitle: "Apprenticeship Ended",
    originalBookletSection: "Section 6",
    requirementKind: "mandatory",
    title: "Results Confirmation Email from EPAO Evidence",
    applicability: "Once EPA results are issued",
    isRecurring: false,
    endOfProgramme: true,
  },
  {
    reference: "6.5",
    sectionKey: "ended",
    sectionTitle: "Apprenticeship Ended",
    originalBookletSection: "Section 6",
    requirementKind: "mandatory",
    title: "Feedback Achievement Report from EPAO Evidence",
    applicability: "Once EPA feedback is issued",
    isRecurring: false,
    endOfProgramme: true,
  },
  {
    reference: "6.6",
    sectionKey: "ended",
    sectionTitle: "Apprenticeship Ended",
    originalBookletSection: "Section 6",
    requirementKind: "mandatory",
    title: "EPAO Invoice Evidence (see accounts dept.)",
    applicability: "Accounts — once EPA invoiced",
    isRecurring: false,
    endOfProgramme: true,
  },
  {
    reference: "6.7",
    sectionKey: "ended",
    sectionTitle: "Apprenticeship Ended",
    originalBookletSection: "Section 6",
    requirementKind: "mandatory",
    title: "GTA Contract with EPAO Evidence (see accounts dept.)",
    applicability: "Accounts — EPAO contract evidence",
    isRecurring: false,
    endOfProgramme: true,
  },

  // Section 7 — Off-The-Job Training
  {
    reference: "7.1",
    sectionKey: "otj",
    sectionTitle: "Off-The-Job Training",
    originalBookletSection: "Section 7",
    requirementKind: "mandatory",
    title: "PDR Learner Progress Record",
    applicability: "All programmes",
    isRecurring: true,
    endOfProgramme: false,
  },
  {
    reference: "7.2",
    sectionKey: "otj",
    sectionTitle: "Off-The-Job Training",
    originalBookletSection: "Section 7",
    requirementKind: "mandatory",
    title: "PDR Learner Off-The-Job Training Record",
    applicability: "All programmes",
    isRecurring: true,
    endOfProgramme: false,
  },
  {
    reference: "7.3",
    sectionKey: "otj",
    sectionTitle: "Off-The-Job Training",
    originalBookletSection: "Section 7",
    requirementKind: "mandatory",
    title: "Off-The-Job Training Log Evidence",
    applicability: "All programmes",
    isRecurring: true,
    endOfProgramme: false,
  },
  {
    reference: "7.4",
    sectionKey: "otj",
    sectionTitle: "Off-The-Job Training",
    originalBookletSection: "Section 7",
    requirementKind: "mandatory",
    title: "Learner Progress Reviews",
    applicability: "All programmes",
    isRecurring: true,
    endOfProgramme: false,
  },
  {
    reference: "7.5",
    sectionKey: "otj",
    sectionTitle: "Off-The-Job Training",
    originalBookletSection: "Section 7",
    requirementKind: "conditional",
    title: "Learner Concern Report Evidence",
    applicability: "Where a concern is raised",
    isRecurring: true,
    endOfProgramme: false,
  },
  {
    reference: "7.6",
    sectionKey: "otj",
    sectionTitle: "Off-The-Job Training",
    originalBookletSection: "Section 7",
    requirementKind: "conditional",
    title: "Break in Learning Evidence",
    applicability: "Where a break in learning occurs",
    isRecurring: false,
    endOfProgramme: false,
  },
  {
    reference: "7.7",
    sectionKey: "otj",
    sectionTitle: "Off-The-Job Training",
    originalBookletSection: "Section 7",
    requirementKind: "conditional",
    title: "Employer Redundancy Evidence",
    applicability: "Where redundancy affects the apprenticeship",
    isRecurring: false,
    endOfProgramme: false,
  },
  {
    reference: "7.8",
    sectionKey: "otj",
    sectionTitle: "Off-The-Job Training",
    originalBookletSection: "Section 7",
    requirementKind: "conditional",
    title: "ALS Support Monthly Record and Associated Evidence",
    applicability: "Where ALS support is in place",
    isRecurring: true,
    endOfProgramme: false,
  },

  // Section 8 — Misc. Items
  {
    reference: "8.1",
    sectionKey: "misc",
    sectionTitle: "Miscellaneous Items",
    originalBookletSection: "Section 8",
    requirementKind: "conditional",
    title: "Miscellaneous Items",
    applicability: "As required by individual circumstances",
    isRecurring: true,
    endOfProgramme: false,
  },
];
