import type { CeaPackDef } from "./types";
import {
  ceaGateway,
  ceaGroup,
  ceaMilestone,
  ceaTask,
  emptySupportItems,
} from "./pack-builder";

/**
 * Seeded from MV14.1 Heavy Level 3 Learner Personal Tracking v1.8 — ST0068.
 * No KSBs — staff map later.
 */
export const HEAVY_CEA_PACK: CeaPackDef = {
  id: "cea-heavy-st0068",
  title: "Heavy Vehicle Apprentice Personal Tracking",
  version: "1.5",
  standardCode: "ST0068",
  standardLabel: "Heavy Vehicle Service and Maintenance Technician (Level 3) — ST0068",
  milestones: [
    ceaMilestone({
      id: "ms-year1",
      title: "Year 1",
      description: "Foundation, housekeeping, tools, routine maintenance, chassis.",
      sortOrder: 1,
      phaseLabel: "Year 1",
    }),
    ceaMilestone({
      id: "ms-gateway1",
      title: "Gateway 1",
      description: "Year 1 gateway assessments before Year 2.",
      sortOrder: 2,
      phaseLabel: "Gateway 1",
    }),
    ceaMilestone({
      id: "ms-year2",
      title: "Year 2",
      description: "Engine, electrical, transmission, customer, diagnostics, inspection.",
      sortOrder: 3,
      phaseLabel: "Year 2",
    }),
    ceaMilestone({
      id: "ms-gateway2",
      title: "Gateway 2",
      description: "Final gateway before EPA.",
      sortOrder: 4,
      phaseLabel: "Gateway 2",
    }),
    ceaMilestone({
      id: "ms-epa",
      title: "EPA",
      description: "End-point assessment.",
      sortOrder: 5,
      phaseLabel: "EPA",
    }),
  ],
  groups: [
    ceaGroup({
      id: "g1",
      milestoneId: "ms-year1",
      number: 1,
      title: "Soft Skills and Behaviours and online courses",
      mandatoryRequired: 1,
      milestoneWeightPercent: 8,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      tasks: [ceaTask("g1", 1, "Foundation skills work booklet")],
    }),
    ceaGroup({
      id: "g2",
      milestoneId: "ms-year1",
      number: 2,
      title: "Health, Safety and Good House Keeping",
      mandatoryRequired: 1,
      milestoneWeightPercent: 8,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      tasks: [ceaTask("g2", 1, "Health and safety work booklet")],
    }),
    ceaGroup({
      id: "g3",
      milestoneId: "ms-year1",
      number: 3,
      title: "Using Hand Tools & Equipment",
      mandatoryRequired: 1,
      milestoneWeightPercent: 8,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      tasks: [
        ceaTask(
          "g3",
          1,
          "Tools and Equipment workbooklet, including mech fab/elec circuit tasks",
        ),
      ],
    }),
    ceaGroup({
      id: "g4",
      milestoneId: "ms-year1",
      number: 4,
      title: "Support Job Roles in the Automotive Industry",
      mandatoryRequired: 1,
      milestoneWeightPercent: 8,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      tasks: [ceaTask("g4", 1, "ERR Booklet + Group 1 unit completed")],
    }),
    ceaGroup({
      id: "g5",
      milestoneId: "ms-year1",
      number: 5,
      title: "Routine Heavy Vehicle Maintenance",
      mandatoryRequired: 2,
      milestoneWeightPercent: 10,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      tasks: [
        ceaTask("g5", 1, "Basic Levels Service"),
        ceaTask("g5", 2, "Basic Drivers Inspection (walk/talk)"),
      ],
    }),
    ceaGroup({
      id: "g6",
      milestoneId: "ms-year1",
      number: 6,
      title: "Remove & Replace Heavy Vehicle Chassis Units and Components",
      mandatoryRequired: 3,
      milestoneWeightPercent: 12,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      tasks: [
        ceaTask("g6", 1, "Remove and install heavy vehicle front pads"),
        ceaTask("g6", 3, "Remove and refit heavy vehicle steering track rod and alignment"),
        ceaTask("g6", 4, "Remove and refit heavy vehicle suspension damper"),
        ceaTask("g6", 5, "Remove and refit heavy vehicle ABS modulator valve"),
        ceaTask("g6", 6, "Carry out test of Night heater"),
      ],
    }),
    ceaGroup({
      id: "g7",
      milestoneId: "ms-year2",
      number: 7,
      title: "Remove & Replace Heavy Vehicle Engine System Units & components",
      mandatoryRequired: 3,
      milestoneWeightPercent: 10,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g7", 1, "Remove and refit heavy vehicle engine mechanical components"),
        ceaTask("g7", 2, "Carry out heavy vehicle engine oil pressure test"),
        ceaTask("g7", 3, "Remove and refit heavy vehicle engine cooling system components"),
        ceaTask("g7", 4, "Remove and refit heavy vehicle engine exhaust system components"),
        ceaTask("g7", 5, "Remove and refit heavy vehicle engine fuel injector"),
      ],
    }),
    ceaGroup({
      id: "g8",
      milestoneId: "ms-year2",
      number: 8,
      title: "Remove & Replace Heavy Vehicle Electrical System units & components",
      mandatoryRequired: 3,
      milestoneWeightPercent: 10,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      knowledgeTestNote: "Minimum 3 of 5 tasks; task 3 & 5 mandatory",
      tasks: [
        ceaTask("g8", 1, "Diagnose headlamp fault with wiring circuit"),
        ceaTask("g8", 2, "Diagnose night heater fault unit"),
        ceaTask("g8", 3, "Remove and refit heavy vehicle starter motor", {
          alwaysMandatory: true,
        }),
        ceaTask("g8", 4, "Diagnose brake lamp fault"),
        ceaTask("g8", 5, "Remove and refit heavy vehicle alternator", {
          alwaysMandatory: true,
        }),
      ],
    }),
    ceaGroup({
      id: "g9",
      milestoneId: "ms-year2",
      number: 9,
      title:
        "Remove & Replace Heavy Vehicle Transmission and Driveline System Units & Comp.",
      mandatoryRequired: 3,
      milestoneWeightPercent: 10,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g9", 1, "Diagnose clutch fault"),
        ceaTask("g9", 2, "Diagnose manual gearbox shift linkage fault"),
        ceaTask("g9", 3, "Diagnose transmission and driveline fault"),
        ceaTask("g9", 4, "Diagnose final drive fault"),
        ceaTask("g9", 5, "Diagnose range change or PTO fault"),
      ],
    }),
    ceaGroup({
      id: "g10",
      milestoneId: "ms-year2",
      number: 10,
      title: "Identify & Agree Customer Service Needs",
      mandatoryRequired: 1,
      milestoneWeightPercent: 5,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g10", 1, "Written Assignment"),
        ceaTask("g10", 2, "Mock Professional Discussion (Optional)"),
      ],
    }),
    ceaGroup({
      id: "g11",
      milestoneId: "ms-year2",
      number: 11,
      title: "Diagnose and Rectify Heavy Vehicle Auxiliary Electrical System Faults",
      mandatoryRequired: 3,
      milestoneWeightPercent: 8,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g11", 1, "Diagnose and rectify a faulty Brake light circuit"),
        ceaTask("g11", 2, "Diagnose and rectify a Starting system fault"),
        ceaTask("g11", 3, "Diagnose and rectify an Auxiliary Lighting system fault"),
        ceaTask("g11", 4, "Diagnose and rectify a Headlamp system fault"),
        ceaTask("g11", 5, "Diagnose and rectify a Central Electrical system fault"),
      ],
    }),
    ceaGroup({
      id: "g12",
      milestoneId: "ms-year2",
      number: 12,
      title: "Inspect Heavy Vehicles to Comply with Legal Requirements",
      mandatoryRequired: 1,
      milestoneWeightPercent: 5,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask(
          "g12",
          1,
          "Carry out Walk and talk Inspection (including DVSA defect coding)",
        ),
      ],
    }),
    ceaGroup({
      id: "g13",
      milestoneId: "ms-year2",
      number: 13,
      title: "Diagnose and Rectify Heavy Vehicle Engine System Faults",
      mandatoryRequired: 3,
      milestoneWeightPercent: 8,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g13", 1, "Diagnose and rectify a heavy vehicle low fuel pressure fault"),
        ceaTask("g13", 2, "Diagnose and rectify a heavy vehicle engine mechanical fault"),
        ceaTask("g13", 3, "Diagnose and rectify a heavy vehicle low oil pressure fault"),
        ceaTask("g13", 5, "Diagnose and rectify a heavy vehicle engine fuel injector fault"),
        ceaTask("g13", 6, "Diagnose and rectify a heavy vehicle engine smoking fault"),
        ceaTask("g13", 7, "Diagnose and rectify a heavy vehicle engine management fault"),
      ],
    }),
    ceaGroup({
      id: "g14",
      milestoneId: "ms-year2",
      number: 14,
      title: "Diagnosis and Rectify Heavy Vehicle Chassis System Faults",
      mandatoryRequired: 3,
      milestoneWeightPercent: 8,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g14", 2, "Diagnose and rectify a heavy vehicle ECAS fault"),
        ceaTask("g14", 3, "Diagnose and rectify a heavy vehicle ABS braking system fault"),
        ceaTask("g14", 4, "Diagnose and rectify a mechanical braking system fault"),
        ceaTask("g14", 5, "Diagnose and rectify a pneumatic braking system fault"),
      ],
    }),
  ],
  gatewayItems: [
    ceaGateway({
      id: "gw1-log",
      milestoneId: "ms-gateway1",
      code: "GW1",
      title: "Gateway 1 assessments",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw2-log",
      milestoneId: "ms-gateway2",
      code: "GW2",
      title: "Gateway 2 assessments",
      status: "not_started",
    }),
  ],
  supportItems: emptySupportItems(),
};
