import type { CeaPackDef } from "./types";
import {
  ceaGateway,
  ceaGroup,
  ceaMilestone,
  ceaTask,
  emptySupportItems,
} from "./pack-builder";

/**
 * Seeded from MV15.1 Light Vehicle Standard Level 3 Personal Tracking v1.6 — ST0033.
 * Month brackets from the tracker sheet. No published group % on this sheet.
 * No KSBs — staff map later.
 */
export const LIGHT_CEA_PACK: CeaPackDef = {
  id: "cea-light-st0033",
  title: "Light Vehicle Apprentice Personal Tracking",
  version: "1.5",
  standardCode: "ST0033",
  standardLabel:
    "Motor Vehicle Service and Maintenance Technician — Light Vehicle (Level 3) — ST0033",
  milestones: [
    ceaMilestone({
      id: "ms-0-6",
      title: "0–6 months",
      description: "Soft skills and foundation — groups 1–2.",
      sortOrder: 1,
      phaseLabel: "0–6 months",
      monthStart: 0,
      monthEnd: 6,
      kind: "groups_phase",
    }),
    ceaMilestone({
      id: "ms-7-12",
      title: "7–12 months",
      description: "Routine service and inspection — group 3.",
      sortOrder: 2,
      phaseLabel: "7–12 months",
      monthStart: 7,
      monthEnd: 12,
      kind: "groups_phase",
    }),
    ceaMilestone({
      id: "ms-gateway1",
      title: "Gateway 1",
      description: "Year 1 gateway before diagnosis and repair.",
      sortOrder: 3,
      phaseLabel: "Gateway 1",
      monthStart: 12,
      monthEnd: 12,
      kind: "gateway",
    }),
    ceaMilestone({
      id: "ms-13-24",
      title: "13–24 months",
      description: "Simple and intermediate diagnosis — groups 4–5.",
      sortOrder: 4,
      phaseLabel: "13–24 months",
      monthStart: 13,
      monthEnd: 24,
      kind: "groups_phase",
    }),
    ceaMilestone({
      id: "ms-gateway2",
      title: "Gateway 2",
      description: "Gateway before Year 3 complex diagnosis.",
      sortOrder: 5,
      phaseLabel: "Gateway 2",
      monthStart: 24,
      monthEnd: 24,
      kind: "gateway",
    }),
    ceaMilestone({
      id: "ms-25-34",
      title: "25–34 months",
      description: "Complex diagnosis and major components — groups 6–7.",
      sortOrder: 6,
      phaseLabel: "25–34 months",
      monthStart: 25,
      monthEnd: 34,
      kind: "groups_phase",
    }),
    ceaMilestone({
      id: "ms-epa",
      title: "EPA",
      description: "35–36 months — End-point assessment.",
      sortOrder: 7,
      phaseLabel: "35–36 months",
      monthStart: 35,
      monthEnd: 36,
      kind: "epa",
    }),
  ],
  groups: [
    ceaGroup({
      id: "g1",
      milestoneId: "ms-0-6",
      number: 1,
      title: "Soft Skills and Behaviours",
      mandatoryRequired: 1,
      milestoneWeightPercent: 35,
      yearLabel: "Year 1",
      phaseLabel: "0–6 months",
      tasks: [ceaTask("g1", 1, "Support job roles in the automotive industry")],
    }),
    ceaGroup({
      id: "g2",
      milestoneId: "ms-0-6",
      number: 2,
      title: "Induction and Foundation Skills",
      mandatoryRequired: 4,
      milestoneWeightPercent: 65,
      yearLabel: "Year 1",
      phaseLabel: "0–6 months",
      tasks: [
        ceaTask("g2", 1, "Health and safety Booklet"),
        ceaTask("g2", 2, "Tools and Equipment Booklet"),
        ceaTask("g2", 3, "Electrical circuit tasks and Block fabrication"),
        ceaTask("g2", 4, "ERR booklet"),
      ],
    }),
    ceaGroup({
      id: "g3",
      milestoneId: "ms-7-12",
      number: 3,
      title: "Routine Service and Inspection",
      mandatoryRequired: 2,
      milestoneWeightPercent: 100,
      yearLabel: "Year 1",
      phaseLabel: "7–12 months",
      tasks: [
        ceaTask("g3", 1, "Carry out a pre-work inspection"),
        ceaTask("g3", 2, "Carry out major service"),
        ceaTask("g3", 3, "Remove and replace front and rear brake discs and pads"),
        ceaTask("g3", 4, "Remove and replace rear brake shoes and drums"),
      ],
    }),
    ceaGroup({
      id: "g4",
      milestoneId: "ms-13-24",
      number: 4,
      title: "Simple Diagnosis and Repair",
      mandatoryRequired: 3,
      milestoneWeightPercent: 45,
      yearLabel: "Year 2",
      phaseLabel: "13–24 months",
      knowledgeTestNote: "Task 2 & 3 mandatory",
      tasks: [
        ceaTask("g4", 1, "Remove and refit door latch mechanism"),
        ceaTask("g4", 2, "Remove and refit an alternator", { alwaysMandatory: true }),
        ceaTask("g4", 3, "Remove and refit a starter motor/battery", {
          alwaysMandatory: true,
        }),
        ceaTask("g4", 4, "Remove and refit wheels and tyres"),
        ceaTask("g4", 5, "Remove and refit a steering arm ball joint"),
        ceaTask("g4", 6, "Remove and refit a front suspension strut"),
      ],
    }),
    ceaGroup({
      id: "g5",
      milestoneId: "ms-13-24",
      number: 5,
      title: "Intermediate Diagnosis and Repair",
      mandatoryRequired: 5,
      milestoneWeightPercent: 55,
      yearLabel: "Year 2",
      phaseLabel: "13–24 months",
      tasks: [
        ceaTask("g5", 1, "Check and adjust valve clearances"),
        ceaTask("g5", 2, "Remove and refit a camshaft timing belt"),
        ceaTask("g5", 3, "Remove and refit a cylinder head gasket"),
        ceaTask("g5", 4, "Remove and refit pistons and crankshaft"),
        ceaTask("g5", 5, "Remove and refit a fuel injector"),
        ceaTask("g5", 6, "Remove and refit a radiator"),
        ceaTask("g5", 7, "Carry out an engine compression test"),
        ceaTask("g5", 8, "Carry out a cylinder leakage test"),
        ceaTask("g5", 9, "Carry out a brake efficiency test"),
        ceaTask("g5", 10, "Carry out an emissions test"),
        ceaTask("g5", 11, "Carry out a diagnostic scan for fault codes"),
        ceaTask("g5", 12, "Carry out electrical measurements of a circuit"),
        ceaTask("g5", 13, "Remove and refit a drive/prop shaft"),
      ],
    }),
    ceaGroup({
      id: "g6",
      milestoneId: "ms-25-34",
      number: 6,
      title: "Complex Diagnosis and Repair",
      mandatoryRequired: 5,
      milestoneWeightPercent: 65,
      yearLabel: "Year 3",
      phaseLabel: "25–34 months",
      knowledgeTestNote: "Minimum 3 of 7 from part A and 2 of 6 from part B",
      tasks: [
        ceaTask("g6", 1, "Carry out four-wheel alignment"),
        ceaTask("g6", 2, "Diagnose and rectify brake light circuit"),
        ceaTask("g6", 3, "Diagnose and rectify supplementary restraint system fault"),
        ceaTask("g6", 4, "Diagnose and rectify starter motor circuit fault"),
        ceaTask("g6", 5, "Diagnose and rectify battery charging fault"),
        ceaTask("g6", 6, "Diagnose and rectify wash/wipe fault"),
        ceaTask("g6", 7, "Diagnose and rectify electric mirror fault"),
        ceaTask("g6", 8, "Diagnose and rectify electric window fault"),
        ceaTask("g6", 9, "Diagnose and rectify central locking fault"),
        ceaTask("g6", 10, "Diagnose and rectify an engine management fault"),
        ceaTask("g6", 11, "Diagnose and rectify an ignition fault"),
        ceaTask("g6", 12, "Diagnose and rectify an emission system fault"),
        ceaTask("g6", 13, "Capture diagnostic live data"),
      ],
    }),
    ceaGroup({
      id: "g7",
      milestoneId: "ms-25-34",
      number: 7,
      title: "Complete Systems Understanding and Repair Major Components",
      mandatoryRequired: 3,
      milestoneWeightPercent: 35,
      yearLabel: "Year 3",
      phaseLabel: "25–34 months",
      tasks: [
        ceaTask("g7", 1, "Diagnose and rectify a manual transmission fault"),
        ceaTask("g7", 2, "Diagnose and rectify a hydraulic clutch fault"),
        ceaTask("g7", 3, "Strip and rebuild manual gearbox"),
        ceaTask("g7", 4, "Strip and rebuild a differential"),
        ceaTask("g7", 5, "Strip and rebuild an engine"),
      ],
    }),
  ],
  gatewayItems: [
    ceaGateway({
      id: "gw1-log",
      milestoneId: "ms-gateway1",
      code: "GW1",
      title: "Gateway 1 assessments",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw2-log",
      milestoneId: "ms-gateway2",
      code: "GW2",
      title: "Gateway 2 assessments",
      status: "not_started",
    }),
  ],
  supportItems: emptySupportItems(),
};
