import type { CeaPackDef } from "./types";
import {
  ceaGateway,
  ceaGroup,
  ceaMilestone,
  ceaTask,
  emptySupportItems,
} from "./pack-builder";

/**
 * Seeded from MV16.1 Vehicle Damage Paint Technician Tracker v1.6 — ST0448.
 * No KSBs — staff map later.
 */
export const PAINT_CEA_PACK: CeaPackDef = {
  id: "cea-paint-st0448",
  title: "Vehicle Damage Paint Technician Personal Tracking",
  version: "1.2",
  standardCode: "ST0448",
  standardLabel: "Vehicle Damage Paint Technician (Level 3) — ST0448",
  milestones: [
    ceaMilestone({
      id: "ms-year1",
      title: "Year 1",
      description: "Foundation, tools, substrate prep, plastics.",
      sortOrder: 1,
      phaseLabel: "Year 1",
    }),
    ceaMilestone({
      id: "ms-gateway1",
      title: "Gateway 1",
      description: "Year 1 gateway practicals.",
      sortOrder: 2,
      phaseLabel: "Gateway 1",
    }),
    ceaMilestone({
      id: "ms-year2",
      title: "Year 2",
      description: "Masking, primers, defects, topcoat, blending, colour.",
      sortOrder: 3,
      phaseLabel: "Year 2",
    }),
    ceaMilestone({
      id: "ms-gateway2",
      title: "Gateway 2",
      description: "Year 2 gateway assessments.",
      sortOrder: 4,
      phaseLabel: "Gateway 2",
    }),
    ceaMilestone({
      id: "ms-gateway3",
      title: "Gateway 3",
      description: "Pre-EPA gateway practicals and mock discussion.",
      sortOrder: 5,
      phaseLabel: "Gateway 3",
    }),
    ceaMilestone({
      id: "ms-epa",
      title: "EPA",
      description: "End-point assessment.",
      sortOrder: 6,
      phaseLabel: "EPA",
    }),
  ],
  groups: [
    ceaGroup({
      id: "g1",
      milestoneId: "ms-year1",
      number: 1,
      title: "Foundation Skills",
      mandatoryRequired: 2,
      milestoneWeightPercent: 10,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      tasks: [
        ceaTask("g1", 1, "Foundation skills booklets"),
        ceaTask("g1", 2, "ERR Booklet"),
      ],
    }),
    ceaGroup({
      id: "g2",
      milestoneId: "ms-year1",
      number: 2,
      title: "Tools and Equipment used in Automotive Refinishing",
      mandatoryRequired: 2,
      milestoneWeightPercent: 10,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      tasks: [
        ceaTask("g2", 1, "Tools and equipment used in automotive refinishing"),
        ceaTask("g2", 2, "Maintaining and testing spray guns"),
      ],
    }),
    ceaGroup({
      id: "g3",
      milestoneId: "ms-year1",
      number: 3,
      title: "Pre-Painted and Substrate Preparation",
      mandatoryRequired: 3,
      milestoneWeightPercent: 15,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      tasks: [
        ceaTask("g3", 1, "Preparation of a new steel panel"),
        ceaTask("g3", 2, "Preparation of an aluminium panel"),
        ceaTask("g3", 3, "Preparation of a painted panel for blending"),
      ],
    }),
    ceaGroup({
      id: "g4",
      milestoneId: "ms-year1",
      number: 4,
      title: "Working with Plastic Components",
      mandatoryRequired: 1,
      milestoneWeightPercent: 10,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      knowledgeTestNote: "Task 1 required under CEA conditions",
      tasks: [
        ceaTask("g4", 1, "Preparation of a thermoplastic component", {
          alwaysMandatory: true,
        }),
      ],
    }),
    ceaGroup({
      id: "g5",
      milestoneId: "ms-year2",
      number: 5,
      title: "Applying Masking Materials",
      mandatoryRequired: 3,
      milestoneWeightPercent: 10,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g5", 1, "Masking single panel apertures"),
        ceaTask("g5", 2, "Masking vehicle components and trim"),
        ceaTask("g5", 3, "Masking for anti-corrosive material application"),
        ceaTask("g5", 4, "Remote masking techniques"),
      ],
    }),
    ceaGroup({
      id: "g6",
      milestoneId: "ms-year2",
      number: 6,
      title: "Applying Fillers and Foundations Materials",
      mandatoryRequired: 3,
      milestoneWeightPercent: 10,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g6", 1, "Mixing and applying foundation etch primer"),
        ceaTask("g6", 2, "Mixing and applying foundation wet on wet primer"),
        ceaTask("g6", 3, "Mixing and applying foundation high build primer"),
        ceaTask("g6", 4, "Preparation of a repaired and primed panel"),
      ],
    }),
    ceaGroup({
      id: "g7",
      milestoneId: "ms-year2",
      number: 7,
      title: "Identify and Rectify Paint Defects",
      mandatoryRequired: 3,
      milestoneWeightPercent: 8,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g7", 1, "Rectify a minor surface scratch defect"),
        ceaTask("g7", 2, "Rectify a loss of gloss defect"),
        ceaTask("g7", 3, "Rectify dirt inclusion defects"),
      ],
    }),
    ceaGroup({
      id: "g8",
      milestoneId: "ms-year2",
      number: 8,
      title: "Edge to edge topcoat repairs",
      mandatoryRequired: 3,
      milestoneWeightPercent: 10,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g8", 1, "Mixing and applying solid colour basecoat and 2k clear coat"),
        ceaTask("g8", 2, "Mixing and applying a metallic basecoat and 2k clear coat"),
        ceaTask("g8", 3, "Spot repair using metallic basecoat and 2k clear coat"),
        ceaTask(
          "g8",
          4,
          "Mixing and applying a two-stage pearlescent basecoat and 2k clear coat",
        ),
        ceaTask(
          "g8",
          5,
          "Spot repair using two-stage pearlescent basecoat and 2k clear coat",
        ),
      ],
    }),
    ceaGroup({
      id: "g9",
      milestoneId: "ms-year2",
      number: 9,
      title: "Blending and fade out repairs",
      mandatoryRequired: 2,
      milestoneWeightPercent: 8,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask(
          "g9",
          1,
          "Blending and fading out two-stage pearlescent basecoat and 2k clear coat",
        ),
        ceaTask(
          "g9",
          2,
          "Blending and fading out metallic pearlescent basecoat and 2k clear coat",
        ),
        ceaTask(
          "g9",
          3,
          "Blending and fading out three-stage pearlescent basecoat and 2k clear coat",
        ),
      ],
    }),
    ceaGroup({
      id: "g10",
      milestoneId: "ms-year2",
      number: 10,
      title: "Mixing and matching colours",
      mandatoryRequired: 2,
      milestoneWeightPercent: 9,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g10", 1, "Mixing and matching a solid colour basecoat"),
        ceaTask("g10", 2, "Mixing and matching a two-stage pearlescent basecoat"),
        ceaTask("g10", 3, "Mixing and matching a three-stage pearlescent basecoat"),
      ],
    }),
  ],
  gatewayItems: [
    ceaGateway({
      id: "gw1-p1",
      milestoneId: "ms-gateway1",
      code: "PAI-GW1P1",
      title: "Preparation of an E-Coated Panel",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw1-p2",
      milestoneId: "ms-gateway1",
      code: "PAI-GW1P2",
      title: "Preparation of a Repaired Panel",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw1-p3",
      milestoneId: "ms-gateway1",
      code: "PAI-GW1P3",
      title: "Preparation of an Aluminium Panel",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw1-p4",
      milestoneId: "ms-gateway1",
      code: "PAI-GW1P4",
      title: "Preparation of a Plastic Component",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw2-p4",
      milestoneId: "ms-gateway2",
      code: "PAI-GW2P4",
      title: "Mixing, Applying and Preparing High Build Primer",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw3-t1",
      milestoneId: "ms-gateway3",
      code: "GW3-T1",
      title: "Identify Panel Material and Substrate: Repair Process Report",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw3-t2",
      milestoneId: "ms-gateway3",
      code: "GW3-T2",
      title: "New Panel Prep, Apply Foundation (W on W) and Topcoat Application",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw3-t3",
      milestoneId: "ms-gateway3",
      code: "GW3-T3",
      title: "Application of Masking Material for Topcoat Application",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw3-t4",
      milestoneId: "ms-gateway3",
      code: "GW3-T4",
      title: "Basecoat Blend and Lacquer Fadeout",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw3-t5",
      milestoneId: "ms-gateway3",
      code: "GW3-T5",
      title: "3 Stage Pearl Colour Match and Blend",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw3-t6",
      milestoneId: "ms-gateway3",
      code: "GW3-T6",
      title: "Professional Discussion Mock",
      status: "not_started",
    }),
  ],
  supportItems: emptySupportItems(),
};
