import type { CeaPackDef } from "./types";
import {
  ceaGateway,
  ceaGroup,
  ceaMilestone,
  ceaTask,
  emptySupportItems,
} from "./pack-builder";

/**
 * Seeded from MV17.1 Vehicle Damage Panel Technician Tracker v1.5 — ST0403.
 * No KSBs — staff map later.
 */
export const PANEL_CEA_PACK: CeaPackDef = {
  id: "cea-panel-st0403",
  title: "Vehicle Damage Panel Technician Personal Tracking",
  version: "1.3",
  standardCode: "ST0403",
  standardLabel: "Vehicle Damage Panel Technician (Level 3) — ST0403",
  milestones: [
    ceaMilestone({
      id: "ms-year1",
      title: "Year 1",
      description: "Foundation, tools, non-permanent panels, minor damage.",
      sortOrder: 1,
      phaseLabel: "Year 1",
    }),
    ceaMilestone({
      id: "ms-gateway1",
      title: "Gateway 1",
      description: "Year 1 gateway assessments.",
      sortOrder: 2,
      phaseLabel: "Gateway 1",
    }),
    ceaMilestone({
      id: "ms-year2",
      title: "Year 2",
      description: "Construction, joining, permanent panels, major repairs.",
      sortOrder: 3,
      phaseLabel: "Year 2",
    }),
    ceaMilestone({
      id: "ms-gateway2",
      title: "Gateway 2",
      description: "Year 2 gateway after welding techniques.",
      sortOrder: 4,
      phaseLabel: "Gateway 2",
    }),
    ceaMilestone({
      id: "ms-gateway3",
      title: "Gateway 3",
      description: "Pre-EPA gateway practicals and mock discussion.",
      sortOrder: 5,
      phaseLabel: "Gateway 3",
    }),
    ceaMilestone({
      id: "ms-epa",
      title: "EPA",
      description: "End-point assessment.",
      sortOrder: 6,
      phaseLabel: "EPA",
    }),
  ],
  groups: [
    ceaGroup({
      id: "g1",
      milestoneId: "ms-year1",
      number: 1,
      title: "Foundation Skills",
      mandatoryRequired: 2,
      milestoneWeightPercent: 8,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      tasks: [
        ceaTask("g1", 1, "Foundation Skills Booklets"),
        ceaTask("g1", 2, "ERR Booklet"),
      ],
    }),
    ceaGroup({
      id: "g2",
      milestoneId: "ms-year1",
      number: 2,
      title: "Tools and Equipment and Measuring Devices used in Body Repair",
      mandatoryRequired: 2,
      milestoneWeightPercent: 8,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      tasks: [
        ceaTask("g2", 1, "Tools and equipment in accident repair"),
        ceaTask("g2", 2, "Equipment used in accident repair"),
      ],
    }),
    ceaGroup({
      id: "g3",
      milestoneId: "ms-year1",
      number: 3,
      title: "Remove/refit Non-Permanently Fixed Body Panels",
      mandatoryRequired: 3,
      milestoneWeightPercent: 12,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      tasks: [
        ceaTask("g3", 1, "Remove and refit a non-permanently fixed wing"),
        ceaTask("g3", 2, "Remove and refit a non-permanently fixed body panels"),
        ceaTask("g3", 3, "Remove and refit front and rear bumpers"),
        ceaTask("g3", 4, "Remove and refit adjacent body panels"),
      ],
    }),
    ceaGroup({
      id: "g4",
      milestoneId: "ms-year1",
      number: 4,
      title: "Identifying and Rectifying Minor Damage Repairs to Body Panels",
      mandatoryRequired: 2,
      milestoneWeightPercent: 10,
      yearLabel: "Year 1",
      phaseLabel: "Year 1",
      tasks: [
        ceaTask("g4", 1, "Identifying and rectifying minor repairs using body filler"),
        ceaTask("g4", 2, "Identifying and rectifying minor repairs to a metal finish"),
      ],
    }),
    ceaGroup({
      id: "g5",
      milestoneId: "ms-year2",
      number: 5,
      title: "Vehicle Construction and Materials",
      mandatoryRequired: 2,
      milestoneWeightPercent: 8,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g5", 1, "Vehicle construction"),
        ceaTask("g5", 2, "Remove and refit a non-permanently front door"),
      ],
    }),
    ceaGroup({
      id: "g6",
      milestoneId: "ms-year2",
      number: 6,
      title: "Resistance Spot Welding",
      mandatoryRequired: 2,
      milestoneWeightPercent: 8,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g6", 1, "Resistance spot welding"),
        ceaTask("g6", 2, "Resistance spot welding testing"),
      ],
    }),
    ceaGroup({
      id: "g7",
      milestoneId: "ms-year2",
      number: 7,
      title: "Metal active gas (MAG) welding techniques",
      mandatoryRequired: 2,
      milestoneWeightPercent: 8,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g7", 1, "Metal active gas (MAG) welding"),
        ceaTask("g7", 2, "Metal active gas (MAG) welding testing"),
      ],
    }),
    ceaGroup({
      id: "g8",
      milestoneId: "ms-year2",
      number: 8,
      title: "Metal Inert Gas (MIG) Brazing Techniques",
      mandatoryRequired: 2,
      milestoneWeightPercent: 8,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g8", 1, "Metal inert gas (MIG) brazing techniques"),
        ceaTask("g8", 2, "Metal inert gas (MIG) brazing testing"),
      ],
    }),
    ceaGroup({
      id: "g9",
      milestoneId: "ms-year2",
      number: 9,
      title: "Removing and Replacing Permanently Fixed Body Panels",
      mandatoryRequired: 1,
      milestoneWeightPercent: 8,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      knowledgeTestNote: "Task 1 required under CEA conditions",
      tasks: [
        ceaTask("g9", 1, "Remove and replace a rear panel", { alwaysMandatory: true }),
      ],
    }),
    ceaGroup({
      id: "g10",
      milestoneId: "ms-year2",
      number: 10,
      title: "Identifying and Rectifying Major Damage Repairs to Body Panels",
      mandatoryRequired: 2,
      milestoneWeightPercent: 8,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g10", 1, "Rectification of a severely distorted body panel"),
        ceaTask("g10", 2, "Rectification of a damaged body panel with difficult access"),
        ceaTask("g10", 3, "Remove and replace a part sill section"),
      ],
    }),
    ceaGroup({
      id: "g11",
      milestoneId: "ms-year2",
      number: 11,
      title: "Tungsten Inert Gas (TIG) Welding Techniques",
      mandatoryRequired: 0,
      milestoneWeightPercent: 4,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [],
    }),
    ceaGroup({
      id: "g12",
      milestoneId: "ms-year2",
      number: 12,
      title: "Adhesive Bonding Techniques",
      mandatoryRequired: 2,
      milestoneWeightPercent: 5,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      tasks: [
        ceaTask("g12", 1, "Rectification of damage plastic components"),
        ceaTask("g12", 2, "Remove and replace a bonded panel"),
      ],
    }),
    ceaGroup({
      id: "g13",
      milestoneId: "ms-year2",
      number: 13,
      title: "Identify and Rectify Body Misalignment",
      mandatoryRequired: 1,
      milestoneWeightPercent: 5,
      yearLabel: "Year 2",
      phaseLabel: "Year 2",
      knowledgeTestNote: "Task 1 under CEA conditions",
      tasks: [
        ceaTask("g13", 1, "Identify and rectify vehicle body misalignment", {
          alwaysMandatory: true,
        }),
      ],
    }),
  ],
  gatewayItems: [
    ceaGateway({
      id: "gw1-log",
      milestoneId: "ms-gateway1",
      code: "GW1",
      title: "Gateway 1 assessments",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw2-log",
      milestoneId: "ms-gateway2",
      code: "GW2",
      title: "Gateway 2 assessments",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw3-t1",
      milestoneId: "ms-gateway3",
      code: "GW3-T1",
      title: "Remove and Replace Bolt on Body Panels",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw3-t2",
      milestoneId: "ms-gateway3",
      code: "GW3-T2",
      title: "Repair using Panel Pulling Equipment and Body Filler",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw3-t3",
      milestoneId: "ms-gateway3",
      code: "GW3-T3",
      title: "Rectify Vehicle Misalignment",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw3-t4",
      milestoneId: "ms-gateway3",
      code: "GW3-T4",
      title: "Joining Technology",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw3-t5",
      milestoneId: "ms-gateway3",
      code: "GW3-T5",
      title: "Methods Deviation",
      status: "not_started",
    }),
    ceaGateway({
      id: "gw3-t6",
      milestoneId: "ms-gateway3",
      code: "GW3-T6",
      title: "Mock Professional Discussion",
      status: "not_started",
    }),
  ],
  supportItems: emptySupportItems(),
};
