import type { ChatGifAttachment } from "./types";

export type ChatEmojiCategory = {
  id: string;
  label: string;
  /** Category tab icon (emoji glyph). */
  icon: string;
  emojis: string[];
};

export type ChatGifMood = {
  id: string;
  label: string;
  icon: string;
  /** Tag used to filter the curated (offline fallback) GIF catalog. */
  tag: string | null;
  /** Search term sent to the live GIF API. Null = trending feed. */
  searchTerm: string | null;
};

export type ChatStickerMood = {
  id: string;
  label: string;
  icon: string;
  /** Offline fallback tag filter. */
  tag: string | null;
  /** Live GIPHY sticker search term. Null = trending stickers. */
  searchTerm: string | null;
};

export type ChatStickerOption = {
  id: string;
  title: string;
  url: string;
  previewUrl: string;
  stillUrl?: string;
  tags: string[];
};

/** WhatsApp-style emoji categories for the tray. */
export const CHAT_EMOJI_CATEGORIES: ChatEmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys & People",
    icon: "😊",
    emojis: [
      "😀",
      "😁",
      "😂",
      "🤣",
      "😊",
      "😇",
      "🙂",
      "😉",
      "😍",
      "🤩",
      "😘",
      "😗",
      "😋",
      "😜",
      "🤪",
      "😎",
      "🤓",
      "🧐",
      "🤔",
      "😑",
      "😶",
      "🙄",
      "😏",
      "😣",
      "😥",
      "😮",
      "😯",
      "😪",
      "😫",
      "🥱",
      "😴",
      "😌",
      "😛",
      "😒",
      "😓",
      "😔",
      "😕",
      "🙃",
      "🤑",
      "😲",
      "☹️",
      "🙁",
      "😖",
      "😞",
      "😟",
      "😤",
      "😢",
      "😭",
      "😦",
      "😧",
      "😨",
      "😩",
      "🤯",
      "😬",
      "😰",
      "😱",
      "🥵",
      "🥶",
      "😳",
      "🤪",
      "😵",
      "😡",
      "😠",
      "🤬",
      "😷",
      "🤒",
      "🤕",
      "🤢",
      "🤮",
      "🤧",
      "🫡",
      "🤗",
      "🤭",
      "🤫",
      "🤥",
      "😶‍🌫️",
      "😐",
      "🤨",
      "😯",
      "👍",
      "👎",
      "👏",
      "🙌",
      "👐",
      "🤝",
      "🙏",
      "💪",
      "🦾",
      "🖐️",
      "✋",
      "🖖",
      "👌",
      "🤌",
      "🤏",
      "✌️",
      "🤞",
      "🤟",
      "🤘",
      "🤙",
      "👈",
      "👉",
      "👆",
      "👇",
      "☝️",
      "👋",
      "🤚",
      "💅",
      "✍️",
      "👀",
      "👁️",
      "👅",
      "👄",
      "💋",
      "🩸",
    ],
  },
  {
    id: "nature",
    label: "Animals & Nature",
    icon: "🐻",
    emojis: [
      "🐶",
      "🐱",
      "🐭",
      "🐹",
      "🐰",
      "🦊",
      "🐻",
      "🐼",
      "🐨",
      "🐯",
      "🦁",
      "🐮",
      "🐷",
      "🐸",
      "🐵",
      "🙈",
      "🙉",
      "🙊",
      "🦄",
      "🐝",
      "🐛",
      "🦋",
      "🐌",
      "🐞",
      "🐜",
      "🦟",
      "🦗",
      "🕷️",
      "🐢",
      "🐍",
      "🦎",
      "🦖",
      "🦕",
      "🐙",
      "🦑",
      "🦐",
      "🦞",
      "🦀",
      "🐡",
      "🐠",
      "🐟",
      "🐬",
      "🐳",
      "🐋",
      "🦈",
      "🌱",
      "🌲",
      "🌳",
      "🌴",
      "🌵",
      "🌾",
      "🌿",
      "☘️",
      "🍀",
      "🍁",
      "🍂",
      "🍃",
      "🌺",
      "🌻",
      "🌹",
      "🌷",
      "🌼",
      "🌸",
      "💐",
      "🍄",
      "🌰",
      "🌍",
      "🌎",
      "🌏",
      "🌕",
      "🌙",
      "⭐",
      "🌟",
      "✨",
      "⚡",
      "🔥",
      "💧",
      "🌊",
    ],
  },
  {
    id: "food",
    label: "Food & Drink",
    icon: "🍔",
    emojis: [
      "🍏",
      "🍎",
      "🍐",
      "🍊",
      "🍋",
      "🍌",
      "🍉",
      "🍇",
      "🍓",
      "🫐",
      "🍈",
      "🍒",
      "🍑",
      "🥭",
      "🍍",
      "🥥",
      "🥝",
      "🍅",
      "🍆",
      "🥑",
      "🥦",
      "🥬",
      "🥒",
      "🌶️",
      "🌽",
      "🥕",
      "🧄",
      "🧅",
      "🥔",
      "🍠",
      "🥐",
      "🥯",
      "🍞",
      "🥖",
      "🥨",
      "🧀",
      "🥚",
      "🍳",
      "🧈",
      "🥞",
      "🧇",
      "🥓",
      "🥩",
      "🍗",
      "🍖",
      "🦴",
      "🌭",
      "🍔",
      "🍟",
      "🍕",
      "🫓",
      "🥪",
      "🥙",
      "🧆",
      "🌮",
      "🌯",
      "🥗",
      "🥘",
      "🥫",
      "🍝",
      "🍜",
      "🍲",
      "🍛",
      "🍣",
      "🍱",
      "🥟",
      "🦪",
      "🍤",
      "🍙",
      "🍚",
      "🍘",
      "🍥",
      "🥠",
      "🥮",
      "🍢",
      "🍡",
      "🍧",
      "🍨",
      "🍦",
      "🥧",
      "🧁",
      "🍰",
      "🎂",
      "🍮",
      "🍭",
      "🍬",
      "🍫",
      "🍿",
      "🍩",
      "🍪",
      "🌰",
      "🥜",
      "🍯",
      "🥛",
      "🍼",
      "☕",
      "🫖",
      "🍵",
      "🧃",
      "🥤",
      "🧋",
      "🍶",
      "🍺",
      "🍻",
      "🥂",
      "🍷",
      "🥃",
      "🍸",
      "🍹",
      "🧉",
      "🍾",
      "🧊",
    ],
  },
  {
    id: "activity",
    label: "Activity",
    icon: "⚽",
    emojis: [
      "⚽",
      "🏀",
      "🏈",
      "⚾",
      "🥎",
      "🎾",
      "🏐",
      "🏉",
      "🥏",
      "🎱",
      "🪀",
      "🏓",
      "🏸",
      "🏒",
      "🏑",
      "🥍",
      "🏏",
      "🪃",
      "🥅",
      "⛳",
      "🪁",
      "🏹",
      "🎣",
      "🤿",
      "🥊",
      "🥋",
      "🎽",
      "🛹",
      "🛼",
      "🛷",
      "⛸️",
      "🥌",
      "🎿",
      "⛷️",
      "🏂",
      "🪂",
      "🏋️",
      "🤼",
      "🤸",
      "⛹️",
      "🤺",
      "🤾",
      "🏌️",
      "🏇",
      "🧘",
      "🏄",
      "🏊",
      "🤽",
      "🚣",
      "🧗",
      "🚵",
      "🚴",
      "🏆",
      "🥇",
      "🥈",
      "🥉",
      "🏅",
      "🎖️",
      "🏵️",
      "🎗️",
      "🎫",
      "🎟️",
      "🎪",
      "🤹",
      "🎭",
      "🩰",
      "🎨",
      "🎬",
      "🎤",
      "🎧",
      "🎼",
      "🎹",
      "🥁",
      "🪘",
      "🎷",
      "🎺",
      "🪗",
      "🎸",
      "🪕",
      "🎻",
      "🎲",
      "♟️",
      "🎯",
      "🎳",
      "🎮",
      "🎰",
      "🧩",
    ],
  },
  {
    id: "travel",
    label: "Travel & Places",
    icon: "🚗",
    emojis: [
      "🚗",
      "🚕",
      "🚙",
      "🚌",
      "🚎",
      "🏎️",
      "🚓",
      "🚑",
      "🚒",
      "🚐",
      "🛻",
      "🚚",
      "🚛",
      "🚜",
      "🦯",
      "🦽",
      "🦼",
      "🛴",
      "🚲",
      "🛵",
      "🏍️",
      "🛺",
      "🚨",
      "🚔",
      "🚍",
      "🚘",
      "🚖",
      "🚡",
      "🚠",
      "🚟",
      "🚃",
      "🚋",
      "🚞",
      "🚝",
      "🚄",
      "🚅",
      "🚈",
      "🚂",
      "🚆",
      "🚇",
      "🚊",
      "🚉",
      "✈️",
      "🛫",
      "🛬",
      "🛩️",
      "💺",
      "🛰️",
      "🚀",
      "🛸",
      "🚁",
      "🛶",
      "⛵",
      "🚤",
      "🛥️",
      "🛳️",
      "⛴️",
      "🚢",
      "⚓",
      "🪝",
      "⛽",
      "🚧",
      "🚦",
      "🚥",
      "🚏",
      "🗺️",
      "🗿",
      "🗽",
      "🗼",
      "🏰",
      "🏯",
      "🏟️",
      "🎡",
      "🎢",
      "🎠",
      "⛲",
      "⛱️",
      "🏖️",
      "🏝️",
      "🏜️",
      "🌋",
      "⛰️",
      "🏔️",
      "🗻",
      "🏕️",
      "⛺",
      "🏠",
      "🏡",
      "🏘️",
      "🏚️",
      "🏗️",
      "🏭",
      "🏢",
      "🏬",
      "🏣",
      "🏤",
      "🏥",
      "🏦",
      "🏨",
      "🏪",
      "🏫",
      "🏩",
      "💒",
      "🏛️",
      "⛪",
      "🕌",
      "🕍",
      "🛕",
      "🕋",
      "⛩️",
      "🛤️",
      "🛣️",
      "🗾",
      "🎑",
      "🏞️",
      "🌅",
      "🌄",
      "🌠",
      "🎇",
      "🎆",
      "🌇",
      "🌆",
      "🏙️",
      "🌃",
      "🌌",
      "🌉",
      "🌁",
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: "💡",
    emojis: [
      "⌚",
      "📱",
      "📲",
      "💻",
      "⌨️",
      "🖥️",
      "🖨️",
      "🖱️",
      "🖲️",
      "🕹️",
      "🗜️",
      "💽",
      "💾",
      "💿",
      "📀",
      "📼",
      "📷",
      "📸",
      "📹",
      "🎥",
      "📽️",
      "🎞️",
      "📞",
      "☎️",
      "📟",
      "📠",
      "📺",
      "📻",
      "🎙️",
      "🎚️",
      "🎛️",
      "🧭",
      "⏱️",
      "⏲️",
      "⏰",
      "🕰️",
      "⌛",
      "⏳",
      "📡",
      "🔋",
      "🔌",
      "💡",
      "🔦",
      "🕯️",
      "🧯",
      "🛢️",
      "💸",
      "💵",
      "💴",
      "💶",
      "💷",
      "💰",
      "💳",
      "💎",
      "⚖️",
      "🪜",
      "🧰",
      "🪛",
      "🔧",
      "🔨",
      "⚒️",
      "🛠️",
      "⛏️",
      "🪚",
      "🔩",
      "⚙️",
      "🪤",
      "🧱",
      "⛓️",
      "🧲",
      "🔫",
      "💣",
      "🧨",
      "🪓",
      "🔪",
      "🗡️",
      "⚔️",
      "🛡️",
      "🚬",
      "⚰️",
      "🪦",
      "⚱️",
      "🏺",
      "🔮",
      "📿",
      "🧿",
      "💈",
      "⚗️",
      "🔭",
      "🔬",
      "🕳️",
      "🩹",
      "🩺",
      "💊",
      "💉",
      "🩸",
      "🧬",
      "🦠",
      "🧫",
      "🧪",
      "🌡️",
      "🧹",
      "🪠",
      "🧺",
      "🧻",
      "🚽",
      "🚰",
      "🚿",
      "🛁",
      "🛀",
      "🧼",
      "🪥",
      "🪒",
      "🧽",
      "🪣",
      "🧴",
      "🛎️",
      "🔑",
      "🗝️",
      "🚪",
      "🪑",
      "🛋️",
      "🛏️",
      "🛌",
      "🧸",
      "🪆",
      "🖼️",
      "🪞",
      "🪟",
      "🛍️",
      "🛒",
      "🎁",
      "🎈",
      "🎏",
      "🎀",
      "🪄",
      "🪅",
      "🎊",
      "🎉",
      "🎎",
      "🏮",
      "🎐",
      "🧧",
      "✉️",
      "📩",
      "📨",
      "📧",
      "💌",
      "📥",
      "📤",
      "📦",
      "🏷️",
      "🪧",
      "📪",
      "📫",
      "📬",
      "📭",
      "📮",
      "📯",
      "📜",
      "📃",
      "📄",
      "📑",
      "🧾",
      "📊",
      "📈",
      "📉",
      "🗒️",
      "🗓️",
      "📆",
      "📅",
      "🗑️",
      "📇",
      "🗃️",
      "🗳️",
      "🗄️",
      "📋",
      "📁",
      "📂",
      "🗂️",
      "📰",
      "📓",
      "📔",
      "📒",
      "📕",
      "📗",
      "📘",
      "📙",
      "📚",
      "📖",
      "🔖",
      "🧷",
      "🔗",
      "📎",
      "🖇️",
      "📐",
      "📏",
      "🧮",
      "📌",
      "📍",
      "✂️",
      "🖊️",
      "🖋️",
      "✒️",
      "🖌️",
      "🖍️",
      "📝",
      "✏️",
      "🔍",
      "🔎",
      "🔏",
      "🔐",
      "🔒",
      "🔓",
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "❤️",
    emojis: [
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "💔",
      "❣️",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💘",
      "💝",
      "💟",
      "☮️",
      "✝️",
      "☪️",
      "🕉️",
      "☸️",
      "✡️",
      "🔯",
      "🕎",
      "☯️",
      "☦️",
      "🛐",
      "⛎",
      "♈",
      "♉",
      "♊",
      "♋",
      "♌",
      "♍",
      "♎",
      "♏",
      "♐",
      "♑",
      "♒",
      "♓",
      "🆔",
      "⚛️",
      "🉑",
      "☢️",
      "☣️",
      "📴",
      "📳",
      "🈶",
      "🈚",
      "🈸",
      "🈺",
      "🈷️",
      "✴️",
      "🆚",
      "💮",
      "🉐",
      "㊙️",
      "㊗️",
      "🈴",
      "🈵",
      "🈹",
      "🈲",
      "🅰️",
      "🅱️",
      "🆎",
      "🆑",
      "🅾️",
      "🆘",
      "❌",
      "⭕",
      "🛑",
      "⛔",
      "📛",
      "🚫",
      "💯",
      "💢",
      "♨️",
      "🚷",
      "🚯",
      "🚳",
      "🚱",
      "🔞",
      "📵",
      "🚭",
      "❗",
      "❕",
      "❓",
      "❔",
      "‼️",
      "⁉️",
      "🔅",
      "🔆",
      "〽️",
      "⚠️",
      "🚸",
      "🔱",
      "⚜️",
      "🔰",
      "♻️",
      "✅",
      "🈯",
      "💹",
      "❇️",
      "✳️",
      "❎",
      "🌐",
      "💠",
      "Ⓜ️",
      "🌀",
      "💤",
      "🏧",
      "🚾",
      "♿",
      "🅿️",
      "🛗",
      "🈳",
      "🈂️",
      "🛂",
      "🛃",
      "🛄",
      "🛅",
      "🚹",
      "🚺",
      "🚼",
      "⚧️",
      "🚻",
      "🚮",
      "🎦",
      "📶",
      "🈁",
      "🔣",
      "ℹ️",
      "🔤",
      "🔡",
      "🔠",
      "🆖",
      "🆗",
      "🆙",
      "🆒",
      "🆕",
      "🆓",
      "0️⃣",
      "1️⃣",
      "2️⃣",
      "3️⃣",
      "4️⃣",
      "5️⃣",
      "6️⃣",
      "7️⃣",
      "8️⃣",
      "9️⃣",
      "🔟",
      "🔢",
      "#️⃣",
      "*️⃣",
      "⏏️",
      "▶️",
      "⏸️",
      "⏯️",
      "⏹️",
      "⏺️",
      "⏭️",
      "⏮️",
      "⏩",
      "⏪",
      "⏫",
      "⏬",
      "◀️",
      "🔼",
      "🔽",
      "➡️",
      "⬅️",
      "⬆️",
      "⬇️",
      "↗️",
      "↘️",
      "↙️",
      "↖️",
      "↕️",
      "↔️",
      "↪️",
      "↩️",
      "⤴️",
      "⤵️",
      "🔀",
      "🔁",
      "🔂",
      "🔄",
      "🔃",
      "🎵",
      "🎶",
      "➕",
      "➖",
      "➗",
      "✖️",
      "♾️",
      "💲",
      "💱",
      "™️",
      "©️",
      "®️",
      "👁️‍🗨️",
      "🔚",
      "🔙",
      "🔛",
      "🔝",
      "🔜",
      "〰️",
      "➰",
      "➿",
      "✔️",
      "☑️",
      "🔘",
      "🔴",
      "🟠",
      "🟡",
      "🟢",
      "🔵",
      "🟣",
      "⚫",
      "⚪",
      "🟤",
      "🔺",
      "🔻",
      "🔸",
      "🔹",
      "🔶",
      "🔷",
      "🔳",
      "🔲",
      "▪️",
      "▫️",
      "◾",
      "◽",
      "◼️",
      "◻️",
      "🟥",
      "🟧",
      "🟨",
      "🟩",
      "🟦",
      "🟪",
      "⬛",
      "⬜",
      "🟫",
      "🔈",
      "🔇",
      "🔉",
      "🔊",
      "🔔",
      "🔕",
      "📣",
      "📢",
      "💬",
      "💭",
      "🗯️",
      "♠️",
      "♣️",
      "♥️",
      "♦️",
      "🃏",
      "🎴",
      "🀄",
      "🕐",
      "🕑",
      "🕒",
      "🕓",
      "🕔",
      "🕕",
      "🕖",
      "🕗",
      "🕘",
      "🕙",
      "🕚",
      "🕛",
    ],
  },
  {
    id: "flags",
    label: "Flags",
    icon: "🏁",
    emojis: [
      "🏁",
      "🚩",
      "🎌",
      "🏴",
      "🏳️",
      "🏳️‍🌈",
      "🏳️‍⚧️",
      "🏴‍☠️",
      "🇬🇧",
      "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
      "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
      "🇮🇪",
      "🇺🇸",
      "🇨🇦",
      "🇦🇺",
      "🇳🇿",
      "🇫🇷",
      "🇩🇪",
      "🇪🇸",
      "🇮🇹",
      "🇵🇹",
      "🇳🇱",
      "🇧🇪",
      "🇨🇭",
      "🇦🇹",
      "🇸🇪",
      "🇳🇴",
      "🇩🇰",
      "🇫🇮",
      "🇵🇱",
      "🇺🇦",
      "🇮🇳",
      "🇵🇰",
      "🇧🇩",
      "🇨🇳",
      "🇯🇵",
      "🇰🇷",
      "🇧🇷",
      "🇲🇽",
      "🇦🇷",
      "🇿🇦",
      "🇳🇬",
      "🇪🇬",
      "🇰🇪",
      "🇹🇷",
      "🇸🇦",
      "🇦🇪",
      "🇶🇦",
      "🇸🇬",
      "🇲🇾",
      "🇹🇭",
      "🇻🇳",
      "🇵🇭",
      "🇮🇩",
    ],
  },
];

export const CHAT_GIF_MOODS: ChatGifMood[] = [
  { id: "trending", label: "Trending", icon: "📈", tag: null, searchTerm: null },
  { id: "happy", label: "Happy", icon: "😊", tag: "hello", searchTerm: "happy" },
  { id: "sad", label: "Sad", icon: "😢", tag: "thinking", searchTerm: "sad" },
  { id: "love", label: "Love", icon: "❤️", tag: "thanks", searchTerm: "love" },
  { id: "yes", label: "Agree", icon: "👍", tag: "yes", searchTerm: "thumbs up" },
  {
    id: "celebrate",
    label: "Celebrate",
    icon: "🎉",
    tag: "celebrate",
    searchTerm: "celebration",
  },
  { id: "work", label: "Work", icon: "💼", tag: "work", searchTerm: "working hard" },
];

function giphyAsset(id: string, file: string): string {
  return `https://media.giphy.com/media/${id}/${file}`;
}

export const CHAT_STICKER_MOODS: ChatStickerMood[] = [
  { id: "trending", label: "Trending", icon: "📈", tag: null, searchTerm: null },
  { id: "hello", label: "Hello", icon: "👋", tag: "hello", searchTerm: "hello" },
  { id: "love", label: "Love", icon: "❤️", tag: "love", searchTerm: "love" },
  { id: "thanks", label: "Thanks", icon: "🙏", tag: "thanks", searchTerm: "thank you" },
  { id: "yes", label: "Agree", icon: "👍", tag: "yes", searchTerm: "thumbs up" },
  {
    id: "celebrate",
    label: "Celebrate",
    icon: "🎉",
    tag: "celebrate",
    searchTerm: "celebrate",
  },
  { id: "funny", label: "Funny", icon: "😂", tag: "funny", searchTerm: "funny" },
];

/** Curated animated GIPHY stickers used when the API key is unavailable. */
const STICKER_SEEDS: {
  id: string;
  title: string;
  giphyId: string;
  tags: string[];
}[] = [
  {
    id: "st-thumbs",
    title: "Thumbs up",
    giphyId: "3o7abKhOpu0NwenH3O",
    tags: ["yes", "hello"],
  },
  {
    id: "st-wave",
    title: "Wave",
    giphyId: "3oz8xIsloV7zOmt81G",
    tags: ["hello"],
  },
  {
    id: "st-heart",
    title: "Heart",
    giphyId: "l0MYt5jPR6QX5pnqM",
    tags: ["love"],
  },
  {
    id: "st-clap",
    title: "Clap",
    giphyId: "7rj2Zg2XCAQWc",
    tags: ["thanks", "celebrate"],
  },
  {
    id: "st-party",
    title: "Party",
    giphyId: "g9582DNuQppxC",
    tags: ["celebrate", "funny"],
  },
  {
    id: "st-thanks",
    title: "Thanks",
    giphyId: "kyLYXonQYYfwYDIeZl",
    tags: ["thanks"],
  },
  {
    id: "st-cool",
    title: "Cool",
    giphyId: "3o6Zt6ML6BklcajjsA",
    tags: ["yes", "funny"],
  },
  {
    id: "st-cat",
    title: "Cat",
    giphyId: "JIX9t2j0ZTN9S",
    tags: ["funny", "hello"],
  },
];

export const CHAT_STICKER_CATALOG: ChatStickerOption[] = STICKER_SEEDS.map(
  (seed) => ({
    id: seed.id,
    title: seed.title,
    url: giphyAsset(seed.giphyId, "200w.webp"),
    previewUrl: giphyAsset(seed.giphyId, "200w.webp"),
    stillUrl: giphyAsset(seed.giphyId, "200_s.gif"),
    tags: seed.tags,
  }),
);

export function searchChatStickers(
  query: string,
  moodTag: string | null = null,
): ChatStickerOption[] {
  const q = query.trim().toLowerCase();
  return CHAT_STICKER_CATALOG.filter((sticker) => {
    if (moodTag && !sticker.tags.includes(moodTag)) return false;
    if (!q) return true;
    const hay = `${sticker.title} ${sticker.tags.join(" ")}`.toLowerCase();
    return hay.includes(q);
  });
}

type GifSeed = {
  id: string;
  title: string;
  giphyId: string;
  tags: string[];
};

const GIF_SEEDS: GifSeed[] = [
  {
    id: "thumbs",
    title: "Thumbs up",
    giphyId: "111ebonMs90YLu",
    tags: ["yes", "ok", "good", "thumbs"],
  },
  {
    id: "clap",
    title: "Clapping",
    giphyId: "26BRuo6sLetdllPAQ",
    tags: ["clap", "well done", "congrats", "celebrate"],
  },
  {
    id: "wave",
    title: "Waving hello",
    giphyId: "3oz8xIsloV7zOmt81G",
    tags: ["hello", "hi", "wave", "thanks"],
  },
  {
    id: "thanks",
    title: "Thank you",
    giphyId: "kyLYXonQYYfwYDIeZl",
    tags: ["thanks", "thank you"],
  },
  {
    id: "thinking",
    title: "Thinking",
    giphyId: "3oriO0OEd9QIDdllqo",
    tags: ["thinking", "hmm", "maybe"],
  },
  {
    id: "celebrate",
    title: "Celebration",
    giphyId: "g9582DNuQppxC",
    tags: ["celebrate", "party", "done"],
  },
  {
    id: "working",
    title: "Hard at work",
    giphyId: "13HgwGsXF0aiGY",
    tags: ["work", "busy", "typing"],
  },
  {
    id: "ok",
    title: "OK",
    giphyId: "3o7abKhOpu0NwenH3O",
    tags: ["ok", "okay", "fine", "yes"],
  },
  {
    id: "laugh",
    title: "Laughing",
    giphyId: "10JhviFuU2gWD6",
    tags: ["lol", "laugh", "funny", "hello"],
  },
  {
    id: "cheers",
    title: "Cheers",
    giphyId: "26u4cqiYI30juCOGY",
    tags: ["yes", "agree", "cheers", "celebrate"],
  },
  {
    id: "cat",
    title: "Happy cat",
    giphyId: "JIX9t2j0ZTN9S",
    tags: ["hello", "cat", "happy", "thanks"],
  },
  {
    id: "highfive",
    title: "High five",
    giphyId: "artj92V8o75VPL7AeQ",
    tags: ["high five", "team", "nice", "celebrate"],
  },
  {
    id: "excited",
    title: "Excited",
    giphyId: "3o6Zt6ML6BklcajjsA",
    tags: ["celebrate", "yes", "excited", "hello"],
  },
  {
    id: "nod",
    title: "Nodding yes",
    giphyId: "26ufdipQqU2lhNA4g",
    tags: ["yes", "agree", "nod"],
  },
  {
    id: "coffee",
    title: "Coffee time",
    giphyId: "l0HlvtIPzPdt2usKs",
    tags: ["coffee", "break", "tired", "work"],
  },
];

export type ChatGifOption = ChatGifAttachment & {
  id: string;
  tags: string[];
  /** Static frame / video poster for the picker grid. */
  stillUrl?: string;
  /** Smaller MP4 for the picker grid (falls back to mp4Url). */
  mp4PreviewUrl?: string;
};

export const CHAT_GIF_CATALOG: ChatGifOption[] = GIF_SEEDS.map((seed) => ({
  id: seed.id,
  type: "gif" as const,
  title: seed.title,
  url: giphyAsset(seed.giphyId, "200w.webp"),
  previewUrl: giphyAsset(seed.giphyId, "200w_d.webp"),
  stillUrl: giphyAsset(seed.giphyId, "200_s.gif"),
  mp4Url: giphyAsset(seed.giphyId, "200w.mp4"),
  mp4PreviewUrl: giphyAsset(seed.giphyId, "100w.mp4"),
  tags: seed.tags,
}));

export function searchChatGifs(
  query: string,
  moodTag: string | null = null,
): ChatGifOption[] {
  const q = query.trim().toLowerCase();
  return CHAT_GIF_CATALOG.filter((gif) => {
    if (moodTag && !gif.tags.includes(moodTag)) return false;
    if (!q) return true;
    const hay = `${gif.title} ${gif.tags.join(" ")}`.toLowerCase();
    return hay.includes(q);
  });
}

export function searchEmojis(query: string, categoryId: string): string[] {
  const category =
    CHAT_EMOJI_CATEGORIES.find((c) => c.id === categoryId) ??
    CHAT_EMOJI_CATEGORIES[0];
  const pool = category?.emojis ?? [];
  const q = query.trim().toLowerCase();
  if (!q) return pool;
  // Unicode emoji search is limited without a name map — filter by including
  // characters from the query when people paste an emoji, else return pool.
  if ([...q].some((ch) => /\p{Extended_Pictographic}/u.test(ch))) {
    return pool.filter((emoji) => emoji.includes(q));
  }
  return pool;
}

export function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
