import { MENTOR_NAME } from "../../data/mentor-caseload";
import { assessSmartto } from "./smartto";
import type { ActionRecord, ActionSourceType } from "./types";

function action(
  partial: Omit<
    ActionRecord,
    "smartto" | "priority" | "evidencePackId" | "signedOffBy" | "signedOffAt" | "signOffNote"
  > & {
    smartto?: ActionRecord["smartto"];
    priority?: ActionRecord["priority"];
    evidencePackId?: string | null;
    signedOffBy?: string | null;
    signedOffAt?: string | null;
    signOffNote?: string | null;
  },
): ActionRecord {
  const smartto =
    partial.smartto ??
    assessSmartto({
      title: partial.title,
      description: partial.description,
      successMeasure: partial.successMeasure,
      dueDate: partial.dueDate,
      checkpointDate: partial.checkpointDate,
      owner: partial.owner,
      evidenceRequirement: partial.evidenceRequirement,
    });
  let priority: ActionRecord["priority"] = partial.priority ?? "medium";
  if (partial.status === "escalated" || partial.escalationStatus) priority = "critical";
  else if (partial.status === "overdue") priority = "high";
  else if (partial.status === "checkpoint_due" || partial.dueDate === "2026-07-17") {
    priority = "high";
  }
  return {
    ...partial,
    smartto,
    priority,
    evidencePackId: partial.evidencePackId ?? null,
    signedOffBy: partial.signedOffBy ?? null,
    signedOffAt: partial.signedOffAt ?? null,
    signOffNote: partial.signOffNote ?? null,
  };
}

function srcLabel(type: ActionSourceType, id: string): string {
  switch (type) {
    case "review":
      return `Review ${id}`;
    case "intervention":
      return `Intervention ${id}`;
    case "employer_concern":
      return `Concern ${id}`;
    case "attendance":
      return "Attendance follow-up";
    case "evidence":
      return "Evidence gap";
    case "epa":
      return "EPA preparation";
    case "programme_recovery":
      return "Programme overdue recovery";
    case "quality":
      return "Quality finding";
    case "management":
      return "Management decision";
    case "support":
      return "Support activity";
    case "tutor":
      return "Tutor follow-up";
    default:
      return id;
  }
}

export let ACTION_RECORDS: ActionRecord[] = [
  // Overdue (4+)
  action({
    actionId: "act-mia-employer-otj",
    title: "Deliver blocked employer opportunity",
    description: "Provide the workplace OTJ opportunity blocked by systems access.",
    learnerId: "lrn-mia-chen",
    learnerName: "Mia Chen",
    employerId: "emp-ashfield",
    employerName: "Ashfield Logistics",
    owner: "Claire Dunn",
    ownerType: "employer",
    createdBy: MENTOR_NAME,
    sourceType: "employer_concern",
    sourceId: "case-ashfield-01",
    sourceLabel: srcLabel("employer_concern", "case-ashfield-01"),
    createdAt: "2026-07-01",
    startDate: "2026-07-01",
    dueDate: "2026-07-10",
    checkpointDate: "2026-07-08",
    successMeasure: "OTJ opportunity delivered and logged",
    evidenceRequirement: "Employer confirmation email",
    evidenceState: "required",
    challengeLevel: "standard",
    status: "overdue",
    progressUpdate: "Access still pending IT",
    completionEvidence: null,
    impact: null,
    escalationStatus: "Escalated to mentor",
    escalationLevel: 1,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-11",
    assignedToMe: true,
    assignedByMe: false,
    missedTargetCount: 1,
  }),
  action({
    actionId: "act-ava-evidence",
    title: "Upload missing BKSB report",
    description: "Apprentice to upload mandatory BKSB diagnostic evidence.",
    learnerId: "lrn-ava-brooks",
    learnerName: "Ava Brooks",
    employerId: "emp-riverside",
    employerName: "Riverside Autocare",
    owner: "Ava Brooks",
    ownerType: "apprentice",
    createdBy: MENTOR_NAME,
    sourceType: "review",
    sourceId: "rev-complete-1",
    sourceLabel: srcLabel("review", "rev-complete-1"),
    createdAt: "2026-07-05",
    startDate: "2026-07-05",
    dueDate: "2026-07-12",
    checkpointDate: "2026-07-10",
    successMeasure: "Mandatory evidence checked in pack",
    evidenceRequirement: "BKSB PDF",
    evidenceState: "required",
    challengeLevel: "foundational",
    status: "overdue",
    progressUpdate: null,
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-12",
    assignedToMe: false,
    assignedByMe: true,
    missedTargetCount: 2,
  }),
  action({
    actionId: "act-ethan-gateway",
    title: "Submit outstanding gateway evidence",
    description: "Close remaining gateway documents before EPA window.",
    learnerId: "lrn-ethan-clarke",
    learnerName: "Ethan Clarke",
    employerId: "emp-hexthorpe",
    employerName: "Hexthorpe Motors",
    owner: "Ethan Clarke",
    ownerType: "apprentice",
    createdBy: MENTOR_NAME,
    sourceType: "programme_recovery",
    sourceId: "int-ethan-overdue",
    sourceLabel: srcLabel("programme_recovery", "int-ethan-overdue"),
    createdAt: "2026-06-20",
    startDate: "2026-06-20",
    dueDate: "2026-07-08",
    checkpointDate: "2026-07-01",
    successMeasure: "Gateway pack complete",
    evidenceRequirement: "Three gateway documents",
    evidenceState: "more_required",
    challengeLevel: "stretch",
    status: "escalated",
    progressUpdate: "One of three documents received",
    completionEvidence: null,
    impact: null,
    escalationStatus: "Escalated",
    escalationLevel: 2,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-05",
    assignedToMe: false,
    assignedByMe: true,
    missedTargetCount: 3,
  }),
  action({
    actionId: "act-riverside-commitment",
    title: "Confirm workplace mentoring hours",
    description: "Employer to confirm mentoring hours in OTJ tracker.",
    learnerId: "lrn-harvey-cole",
    learnerName: "Harvey Cole",
    employerId: "emp-riverside",
    employerName: "Riverside Autocare",
    owner: "Priya Shah",
    ownerType: "employer",
    createdBy: MENTOR_NAME,
    sourceType: "review",
    sourceId: "rev-complete-4",
    sourceLabel: srcLabel("review", "rev-complete-4"),
    createdAt: "2026-07-01",
    startDate: "2026-07-01",
    dueDate: "2026-07-09",
    checkpointDate: "2026-07-07",
    successMeasure: "Hours logged in OTJ tracker",
    evidenceRequirement: "OTJ tracker entries",
    evidenceState: "required",
    challengeLevel: "standard",
    status: "overdue",
    progressUpdate:
      "Claimed mentoring happened, but OTJ tracker shows 0 of 4 planned hours — open the tracker to validate.",
    completionEvidence: null,
    impact: null,
    escalationStatus: "Employer commitment overdue — no OTJ hours in tracker",
    escalationLevel: 2,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-09",
    assignedToMe: true,
    assignedByMe: false,
    missedTargetCount: 2,
    evidencePackId: "otj-harvey-mentoring",
  }),

  // Employer commitments (visible after review)
  action({
    actionId: "act-ashfield-commitment-2",
    title: "Provide admin systems access for apprentice",
    description: "Grant Amelia Frost access to admin systems used in training.",
    learnerId: "lrn-amelia-frost",
    learnerName: "Amelia Frost",
    employerId: "emp-ashfield",
    employerName: "Ashfield Logistics",
    owner: "Claire Dunn",
    ownerType: "employer",
    createdBy: MENTOR_NAME,
    sourceType: "employer_concern",
    sourceId: "case-ashfield-01",
    sourceLabel: srcLabel("employer_concern", "case-ashfield-01"),
    createdAt: "2026-06-25",
    startDate: "2026-06-25",
    dueDate: "2026-07-05",
    checkpointDate: "2026-07-02",
    successMeasure: "Access confirmed by apprentice",
    evidenceRequirement: "Screenshot / confirmation",
    evidenceState: "required",
    challengeLevel: "standard",
    status: "overdue",
    progressUpdate:
      "IT ticket open but access still not granted — apprentice cannot complete admin tasks.",
    completionEvidence: null,
    impact: null,
    escalationStatus: "Escalated — employer systems access still blocked",
    escalationLevel: 1,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-06",
    assignedToMe: true,
    assignedByMe: false,
    missedTargetCount: 1,
  }),
  action({
    actionId: "act-hexthorpe-commitment",
    title: "Schedule workplace mentor catch-up",
    description: "Employer mentor to meet Ethan weekly for four weeks.",
    learnerId: "lrn-ethan-clarke",
    learnerName: "Ethan Clarke",
    employerId: "emp-hexthorpe",
    employerName: "Hexthorpe Motors",
    owner: "Tom Briggs",
    ownerType: "employer",
    createdBy: MENTOR_NAME,
    sourceType: "review",
    sourceId: "rev-mia-open",
    sourceLabel: srcLabel("review", "rev-mia-open"),
    createdAt: "2026-07-10",
    startDate: "2026-07-10",
    dueDate: "2026-07-24",
    checkpointDate: "2026-07-17",
    successMeasure: "Four meetings logged",
    evidenceRequirement: "Meeting notes",
    evidenceState: "required",
    challengeLevel: "standard",
    status: "checkpoint_due",
    progressUpdate: "Only one of four meetings happened — mentor shift pattern changed.",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-16",
    assignedToMe: true,
    assignedByMe: true,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-peak-commitment",
    title: "Release apprentice for additional workshop day",
    description: "Confirm release for catch-up workshop.",
    learnerId: "lrn-noah-reid",
    learnerName: "Noah Reid",
    employerId: "emp-peak",
    employerName: "Peak Power Solutions",
    owner: "Helen Park",
    ownerType: "employer",
    createdBy: MENTOR_NAME,
    sourceType: "attendance",
    sourceId: "att-noah",
    sourceLabel: srcLabel("attendance", "att-noah"),
    createdAt: "2026-07-12",
    startDate: "2026-07-12",
    dueDate: "2026-07-20",
    checkpointDate: "2026-07-18",
    successMeasure: "Release confirmed in writing",
    evidenceRequirement: "Email confirmation",
    evidenceState: "submitted",
    challengeLevel: "standard",
    status: "awaiting_evidence",
    progressUpdate: "Verbal agreement received",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-15",
    assignedToMe: true,
    assignedByMe: true,
    missedTargetCount: 0,
  }),

  // Apprentice targets
  action({
    actionId: "act-liam-k-sb",
    title: "Complete outstanding KSB evidence pack items",
    description: "Close two mandatory KSB evidence gaps before next review.",
    learnerId: "lrn-liam-anderson",
    learnerName: "Liam Anderson",
    employerId: "emp-donvalley",
    employerName: "Don Valley Bodyworks",
    owner: "Liam Anderson",
    ownerType: "apprentice",
    createdBy: MENTOR_NAME,
    sourceType: "intervention",
    sourceId: "int-liam-evidence",
    sourceLabel: srcLabel("intervention", "int-liam-evidence"),
    createdAt: "2026-07-02",
    startDate: "2026-07-02",
    dueDate: "2026-07-18",
    checkpointDate: "2026-07-15",
    successMeasure: "Mandatory gaps closed",
    evidenceRequirement: "Two mandatory evidence items",
    evidenceState: "submitted",
    challengeLevel: "stretch",
    status: "in_progress",
    progressUpdate: "One item uploaded",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-14",
    assignedToMe: false,
    assignedByMe: true,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-chloe-evidence",
    title: "Submit induction evidence pack",
    description: "Complete induction section of the ADM14 pack.",
    learnerId: "lrn-chloe-nash",
    learnerName: "Chloe Nash",
    employerId: "emp-hexthorpe",
    employerName: "Hexthorpe Motors",
    owner: "Chloe Nash",
    ownerType: "apprentice",
    createdBy: MENTOR_NAME,
    sourceType: "evidence",
    sourceId: "lrn-chloe-nash",
    sourceLabel: srcLabel("evidence", "lrn-chloe-nash"),
    createdAt: "2026-07-06",
    startDate: "2026-07-06",
    dueDate: "2026-07-19",
    checkpointDate: "2026-07-15",
    successMeasure: "Induction section complete",
    evidenceRequirement: "Induction documents",
    evidenceState: "required",
    challengeLevel: "foundational",
    status: "not_started",
    progressUpdate: null,
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-06",
    assignedToMe: false,
    assignedByMe: true,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-finley-practice",
    title: "Practise braking system diagnostic checklist",
    description: "Complete three supervised diagnostic practices with reflection.",
    learnerId: "lrn-finley-brooks",
    learnerName: "Finley Brooks",
    employerId: "emp-riverside",
    employerName: "Riverside Autocare",
    owner: "Finley Brooks",
    ownerType: "apprentice",
    createdBy: MENTOR_NAME,
    sourceType: "review",
    sourceId: "rev-complete-10",
    sourceLabel: srcLabel("review", "rev-complete-10"),
    createdAt: "2026-07-08",
    startDate: "2026-07-08",
    dueDate: "2026-07-25",
    checkpointDate: "2026-07-17",
    successMeasure: "Three practice logs reviewed by tutor",
    evidenceRequirement: "Practice log + tutor sign-off",
    evidenceState: "required",
    challengeLevel: "stretch",
    status: "checkpoint_due",
    progressUpdate: "Two practices completed",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-16",
    assignedToMe: false,
    assignedByMe: true,
    missedTargetCount: 1,
  }),
  action({
    actionId: "act-ivy-maths",
    title: "Improve functional skills maths mock score",
    description: "Raise mock score to 70% before gateway.",
    learnerId: "lrn-ivy-marshall",
    learnerName: "Ivy Marshall",
    employerId: "emp-northline",
    employerName: "Northline Services Ltd",
    owner: "Ivy Marshall",
    ownerType: "apprentice",
    createdBy: MENTOR_NAME,
    sourceType: "support",
    sourceId: "support-ivy",
    sourceLabel: srcLabel("support", "support-ivy"),
    createdAt: "2026-07-03",
    startDate: "2026-07-03",
    dueDate: "2026-07-30",
    checkpointDate: "2026-07-20",
    successMeasure: "Mock score ≥ 70%",
    evidenceRequirement: "Mock result sheet",
    evidenceState: "required",
    challengeLevel: "stretch",
    status: "in_progress",
    progressUpdate: "Current mock 58%",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-14",
    assignedToMe: false,
    assignedByMe: true,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-oscar-otj",
    title: "Log weekly off-the-job hours accurately",
    description: "Record OTJ hours within 48 hours of activity.",
    learnerId: "lrn-oscar-hayes",
    learnerName: "Oscar Hayes",
    employerId: "emp-peak",
    employerName: "Peak Power Solutions",
    owner: "Oscar Hayes",
    ownerType: "apprentice",
    createdBy: MENTOR_NAME,
    sourceType: "review",
    sourceId: "rev-complete-2",
    sourceLabel: srcLabel("review", "rev-complete-2"),
    createdAt: "2026-06-28",
    startDate: "2026-06-28",
    dueDate: "2026-07-28",
    checkpointDate: "2026-07-14",
    successMeasure: "Four consecutive weeks logged on time",
    evidenceRequirement: "OTJ tracker entries",
    evidenceState: "accepted",
    challengeLevel: "foundational",
    status: "in_progress",
    progressUpdate: "Two weeks on time",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-14",
    assignedToMe: false,
    assignedByMe: true,
    missedTargetCount: 0,
    evidencePackId: "otj-oscar-weekly",
  }),

  // Mentor / tutor / provider / due today / awaiting evidence
  action({
    actionId: "act-noah-attendance",
    title: "Agree attendance recovery plan",
    description: "Mentor and apprentice agree a four-week attendance recovery plan.",
    learnerId: "lrn-noah-reid",
    learnerName: "Noah Reid",
    employerId: "emp-peak",
    employerName: "Peak Power Solutions",
    owner: MENTOR_NAME,
    ownerType: "mentor",
    createdBy: MENTOR_NAME,
    sourceType: "intervention",
    sourceId: "int-noah-attendance",
    sourceLabel: srcLabel("intervention", "int-noah-attendance"),
    createdAt: "2026-07-08",
    startDate: "2026-07-08",
    dueDate: "2026-07-17",
    checkpointDate: "2026-07-16",
    successMeasure: "Attendance above 85% for 4 weeks",
    evidenceRequirement: "Signed recovery plan",
    evidenceState: "required",
    challengeLevel: "standard",
    status: "in_progress",
    progressUpdate: "Draft plan shared",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-12",
    assignedToMe: true,
    assignedByMe: true,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-dylan-epa",
    title: "Complete EPA readiness checklist",
    description: "Confirm EPA readiness checklist with tutor and mentor sign-off.",
    learnerId: "lrn-dylan-moore",
    learnerName: "Dylan Moore",
    employerId: "emp-peak",
    employerName: "Peak Power Solutions",
    owner: MENTOR_NAME,
    ownerType: "mentor",
    createdBy: MENTOR_NAME,
    sourceType: "epa",
    sourceId: "rev-dylan",
    sourceLabel: srcLabel("epa", "rev-dylan"),
    createdAt: "2026-07-08",
    startDate: "2026-07-08",
    dueDate: "2026-07-16",
    checkpointDate: "2026-07-14",
    successMeasure: "Checklist signed by tutor and mentor",
    evidenceRequirement: "EPA checklist form",
    evidenceState: "submitted",
    challengeLevel: "stretch",
    status: "awaiting_evidence",
    progressUpdate: "Checklist drafted",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-13",
    assignedToMe: true,
    assignedByMe: true,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-finley-tutor",
    title: "Re-teach module assessment criteria",
    description: "Tutor re-teaches assessment criteria and supports resubmission.",
    learnerId: "lrn-finley-brooks",
    learnerName: "Finley Brooks",
    employerId: "emp-riverside",
    employerName: "Riverside Autocare",
    owner: "Daniel Turner",
    ownerType: "tutor",
    createdBy: MENTOR_NAME,
    sourceType: "tutor",
    sourceId: "rev-finley",
    sourceLabel: srcLabel("tutor", "rev-finley"),
    createdAt: "2026-07-10",
    startDate: "2026-07-10",
    dueDate: "2026-07-20",
    checkpointDate: "2026-07-18",
    successMeasure: "Assessment resubmitted",
    evidenceRequirement: "Marked assessment",
    evidenceState: "required",
    challengeLevel: "standard",
    status: "agreed",
    progressUpdate: null,
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-10",
    assignedToMe: false,
    assignedByMe: true,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-harry-provider",
    title: "Arrange additional workshop session",
    description: "Schedule catch-up workshop session for practical hours.",
    learnerId: "lrn-harry-kent",
    learnerName: "Harry Kent",
    employerId: "emp-northline",
    employerName: "Northline Services Ltd",
    owner: "GTA Scheduling",
    ownerType: "provider",
    createdBy: MENTOR_NAME,
    sourceType: "intervention",
    sourceId: "int-ava-progress",
    sourceLabel: srcLabel("intervention", "int-ava-progress"),
    createdAt: "2026-07-09",
    startDate: "2026-07-09",
    dueDate: "2026-07-18",
    checkpointDate: "2026-07-16",
    successMeasure: "Session booked in calendar",
    evidenceRequirement: "Calendar booking",
    evidenceState: "required",
    challengeLevel: "standard",
    status: "not_started",
    progressUpdate: null,
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-09",
    assignedToMe: true,
    assignedByMe: false,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-quality-sampling",
    title: "Respond to quality sampling finding",
    description: "Address incomplete review summary identified in quality sample.",
    learnerId: "lrn-grace-powell",
    learnerName: "Grace Powell",
    employerId: "emp-donvalley",
    employerName: "Don Valley Bodyworks",
    owner: MENTOR_NAME,
    ownerType: "mentor",
    createdBy: "Quality Team",
    sourceType: "quality",
    sourceId: "qf-2026-14",
    sourceLabel: srcLabel("quality", "qf-2026-14"),
    createdAt: "2026-07-11",
    startDate: "2026-07-11",
    dueDate: "2026-07-17",
    checkpointDate: "2026-07-15",
    successMeasure: "Corrected summary reissued",
    evidenceRequirement: "Updated review summary",
    evidenceState: "required",
    challengeLevel: "standard",
    status: "in_progress",
    progressUpdate: "Draft correction prepared",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-16",
    assignedToMe: true,
    assignedByMe: false,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-mgmt-caseload",
    title: "Redistribute overdue review preparation",
    description: "Management decision to rebalance caseload for overdue prep.",
    learnerId: null,
    learnerName: null,
    employerId: null,
    employerName: null,
    owner: MENTOR_NAME,
    ownerType: "manager",
    createdBy: "Operations Manager",
    sourceType: "management",
    sourceId: "mgmt-0726",
    sourceLabel: srcLabel("management", "mgmt-0726"),
    createdAt: "2026-07-14",
    startDate: "2026-07-14",
    dueDate: "2026-07-21",
    checkpointDate: "2026-07-18",
    successMeasure: "Overdue prep queue under 5",
    evidenceRequirement: "Updated caseload report",
    evidenceState: "required",
    challengeLevel: "standard",
    status: "agreed",
    progressUpdate: null,
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-14",
    assignedToMe: true,
    assignedByMe: false,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-sofia-await-ev",
    title: "Provide progress data fix confirmation",
    description: "Confirm progress feed restored after data issue.",
    learnerId: "lrn-sofia-martinez",
    learnerName: "Sofia Martinez",
    employerId: "emp-ashfield",
    employerName: "Ashfield Logistics",
    owner: "GTA Data Team",
    ownerType: "administrator",
    createdBy: MENTOR_NAME,
    sourceType: "management",
    sourceId: "data-sofia",
    sourceLabel: srcLabel("management", "data-sofia"),
    createdAt: "2026-07-12",
    startDate: "2026-07-12",
    dueDate: "2026-07-18",
    checkpointDate: "2026-07-16",
    successMeasure: "Actual progress available in mentor view",
    evidenceRequirement: "System screenshot",
    evidenceState: "submitted",
    challengeLevel: "standard",
    status: "awaiting_evidence",
    progressUpdate: "Fix deployed, awaiting confirmation",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-16",
    assignedToMe: true,
    assignedByMe: true,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-ellie-await",
    title: "Submit employer witness statement",
    description: "Employer to provide witness statement for practical competence.",
    learnerId: "lrn-ellie-scott",
    learnerName: "Ellie Scott",
    employerId: "emp-peak",
    employerName: "Peak Power Solutions",
    owner: "Helen Park",
    ownerType: "employer",
    createdBy: MENTOR_NAME,
    sourceType: "review",
    sourceId: "rev-sign-ellie",
    sourceLabel: srcLabel("review", "rev-sign-ellie"),
    createdAt: "2026-07-02",
    startDate: "2026-07-02",
    dueDate: "2026-07-19",
    checkpointDate: "2026-07-12",
    successMeasure: "Signed witness statement received",
    evidenceRequirement: "Signed PDF",
    evidenceState: "submitted",
    challengeLevel: "standard",
    status: "awaiting_evidence",
    progressUpdate: "Draft received",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-15",
    assignedToMe: true,
    assignedByMe: true,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-amelia-await",
    title: "Upload revised CV evidence",
    description: "Apprentice uploads revised CV for employability module.",
    learnerId: "lrn-amelia-frost",
    learnerName: "Amelia Frost",
    employerId: "emp-ashfield",
    employerName: "Ashfield Logistics",
    owner: "Amelia Frost",
    ownerType: "apprentice",
    createdBy: MENTOR_NAME,
    sourceType: "evidence",
    sourceId: "ev-amelia",
    sourceLabel: srcLabel("evidence", "ev-amelia"),
    createdAt: "2026-07-09",
    startDate: "2026-07-09",
    dueDate: "2026-07-22",
    checkpointDate: "2026-07-16",
    successMeasure: "CV accepted by tutor",
    evidenceRequirement: "CV PDF",
    evidenceState: "submitted",
    challengeLevel: "foundational",
    status: "awaiting_evidence",
    progressUpdate: "Uploaded awaiting tutor review",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-16",
    assignedToMe: false,
    assignedByMe: true,
    missedTargetCount: 0,
  }),

  // Isla Bennett — agreed at completed review (rev-complete-1)
  action({
    actionId: "act-isla-panel-repair",
    title: "Complete supervised panel section repair to workshop standard",
    description:
      "Isla to complete one full panel section repair under workplace mentor supervision, applying correct prep, filler and finish sequence taught in Year 1 college sessions.",
    learnerId: "lrn-isla-bennett",
    learnerName: "Isla Bennett",
    employerId: "emp-donvalley",
    employerName: "Don Valley Bodyworks",
    owner: "Isla Bennett",
    ownerType: "apprentice",
    createdBy: MENTOR_NAME,
    sourceType: "review",
    sourceId: "rev-complete-1",
    sourceLabel: "Progress review 2026-06-28",
    createdAt: "2026-06-28",
    startDate: "2026-06-28",
    dueDate: "2026-07-25",
    checkpointDate: "2026-07-11",
    successMeasure:
      "One supervised repair signed off against workshop quality checklist",
    evidenceRequirement: "Photo evidence + workplace mentor sign-off sheet",
    evidenceState: "submitted",
    challengeLevel: "standard",
    status: "in_progress",
    progressUpdate: "Repair started; filler stage complete, awaiting final finish",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-14",
    assignedToMe: false,
    assignedByMe: true,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-isla-employer-otj",
    title: "Confirm weekly workplace mentoring slots in OTJ tracker",
    description:
      "Mark Holton to diary and log two 30-minute mentoring slots each week so Isla’s off-the-job hours stay accurate for the next review cycle.",
    learnerId: "lrn-isla-bennett",
    learnerName: "Isla Bennett",
    employerId: "emp-donvalley",
    employerName: "Don Valley Bodyworks",
    owner: "Mark Holton",
    ownerType: "employer",
    createdBy: MENTOR_NAME,
    sourceType: "review",
    sourceId: "rev-complete-1",
    sourceLabel: "Progress review 2026-06-28",
    createdAt: "2026-06-28",
    startDate: "2026-06-28",
    dueDate: "2026-07-18",
    checkpointDate: "2026-07-10",
    successMeasure: "Four consecutive weeks with mentoring hours logged",
    evidenceRequirement: "OTJ tracker entries",
    evidenceState: "submitted",
    challengeLevel: "foundational",
    status: "awaiting_evidence",
    progressUpdate:
      "Employer says four weeks are logged in the OTJ tracker — open the tracker below and sign off only if the hours match the plan.",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-16",
    assignedToMe: true,
    assignedByMe: true,
    missedTargetCount: 0,
    evidencePackId: "otj-isla-mentoring",
  }),
  action({
    actionId: "act-isla-ksb-reflect",
    title: "Upload reflective account for two completed KSBs",
    description:
      "Isla to write and upload reflective accounts for the two Year 1 KSBs marked complete in the review, linking workplace examples to standard criteria.",
    learnerId: "lrn-isla-bennett",
    learnerName: "Isla Bennett",
    employerId: "emp-donvalley",
    employerName: "Don Valley Bodyworks",
    owner: "Isla Bennett",
    ownerType: "apprentice",
    createdBy: MENTOR_NAME,
    sourceType: "review",
    sourceId: "rev-complete-1",
    sourceLabel: "Progress review 2026-06-28",
    createdAt: "2026-06-28",
    startDate: "2026-06-28",
    dueDate: "2026-07-20",
    checkpointDate: "2026-07-13",
    successMeasure: "Two reflective accounts accepted by tutor",
    evidenceRequirement: "Reflective account PDFs in evidence pack",
    evidenceState: "accepted",
    challengeLevel: "standard",
    status: "impact_confirmed",
    progressUpdate: "Both accounts accepted",
    completionEvidence: "Tutor acceptance note",
    impact: "Evidence pack now current for Year 1 KSBs discussed in review",
    escalationStatus: null,
    escalationLevel: null,
    closedDate: "2026-07-15",
    closureReason: "Completed with impact confirmed",
    lastUpdate: "2026-07-15",
    assignedToMe: false,
    assignedByMe: true,
    missedTargetCount: 0,
  }),
  // Amendment cycle — action raised while returned for amendment
  action({
    actionId: "act-isla-amend-summary",
    title: "Issue amended review summary to employer",
    description:
      "Provider to re-issue the amended review summary after employer requested clarification on the panel repair target wording.",
    learnerId: "lrn-isla-bennett",
    learnerName: "Isla Bennett",
    employerId: "emp-donvalley",
    employerName: "Don Valley Bodyworks",
    owner: MENTOR_NAME,
    ownerType: "mentor",
    createdBy: MENTOR_NAME,
    sourceType: "review",
    sourceId: "rev-isla-amend",
    sourceLabel: "Progress review (amendment)",
    createdAt: "2026-07-16",
    startDate: "2026-07-16",
    dueDate: "2026-07-18",
    checkpointDate: "2026-07-17",
    successMeasure: "Amended summary issued and employer re-sign requested",
    evidenceRequirement: "Issued summary record",
    evidenceState: "required",
    challengeLevel: "foundational",
    status: "in_progress",
    progressUpdate: "Wording updated; awaiting issue",
    completionEvidence: null,
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: null,
    closureReason: null,
    lastUpdate: "2026-07-16",
    assignedToMe: true,
    assignedByMe: true,
    missedTargetCount: 0,
  }),

  // Completed / impact
  action({
    actionId: "act-grace-complete",
    title: "Confirm employer feedback on last review",
    description: "Employer confirmed feedback captured in previous review cycle.",
    learnerId: "lrn-grace-powell",
    learnerName: "Grace Powell",
    employerId: "emp-donvalley",
    employerName: "Don Valley Bodyworks",
    owner: MENTOR_NAME,
    ownerType: "mentor",
    createdBy: MENTOR_NAME,
    sourceType: "review",
    sourceId: "rev-complete-11",
    sourceLabel: srcLabel("review", "rev-complete-11"),
    createdAt: "2026-06-15",
    startDate: "2026-06-15",
    dueDate: "2026-06-25",
    checkpointDate: "2026-06-20",
    successMeasure: "Feedback logged on review",
    evidenceRequirement: "Review note",
    evidenceState: "accepted",
    challengeLevel: "standard",
    status: "impact_confirmed",
    progressUpdate: "Completed",
    completionEvidence: "Review note attached",
    impact: "Employer engagement improved for next cycle",
    escalationStatus: null,
    escalationLevel: null,
    closedDate: "2026-06-24",
    closureReason: "Completed with impact confirmed",
    lastUpdate: "2026-06-24",
    assignedToMe: true,
    assignedByMe: true,
    missedTargetCount: 0,
  }),
  action({
    actionId: "act-james-complete",
    title: "Complete first practical observation",
    description: "Apprentice completed first observed practical with tutor.",
    learnerId: "lrn-james-wilson",
    learnerName: "James Wilson",
    employerId: "emp-northline",
    employerName: "Northline Services Ltd",
    owner: "James Wilson",
    ownerType: "apprentice",
    createdBy: MENTOR_NAME,
    sourceType: "review",
    sourceId: "rev-sign-james",
    sourceLabel: srcLabel("review", "rev-sign-james"),
    createdAt: "2026-06-01",
    startDate: "2026-06-01",
    dueDate: "2026-06-18",
    checkpointDate: "2026-06-10",
    successMeasure: "Observation signed by tutor",
    evidenceRequirement: "Observation form",
    evidenceState: "accepted",
    challengeLevel: "foundational",
    status: "completed",
    progressUpdate: "Done",
    completionEvidence: "Observation form",
    impact: null,
    escalationStatus: null,
    escalationLevel: null,
    closedDate: "2026-06-17",
    closureReason: "Completed",
    lastUpdate: "2026-06-17",
    assignedToMe: false,
    assignedByMe: true,
    missedTargetCount: 0,
  }),
];

export function getAction(actionId: string): ActionRecord | undefined {
  return ACTION_RECORDS.find((a) => a.actionId === actionId);
}

export function actionsForReview(reviewId: string): ActionRecord[] {
  return ACTION_RECORDS.filter(
    (a) => a.sourceType === "review" && a.sourceId === reviewId,
  );
}

export function previousActionsForLearner(learnerId: string): ActionRecord[] {
  return ACTION_RECORDS.filter(
    (a) =>
      a.learnerId === learnerId &&
      a.status !== "cancelled" &&
      a.status !== "closed" &&
      a.status !== "draft",
  );
}

export function openActionsForLearner(learnerId: string): ActionRecord[] {
  return ACTION_RECORDS.filter(
    (a) =>
      a.learnerId === learnerId &&
      ![
        "completed",
        "impact_confirmed",
        "cancelled",
        "closed",
        "draft",
      ].includes(a.status),
  );
}

export function addAction(record: ActionRecord): void {
  ACTION_RECORDS = [record, ...ACTION_RECORDS];
}

export function updateAction(
  actionId: string,
  patch: Partial<ActionRecord>,
): ActionRecord | undefined {
  const index = ACTION_RECORDS.findIndex((a) => a.actionId === actionId);
  if (index < 0) return undefined;
  const next = { ...ACTION_RECORDS[index], ...patch };
  ACTION_RECORDS = [
    ...ACTION_RECORDS.slice(0, index),
    next,
    ...ACTION_RECORDS.slice(index + 1),
  ];
  return next;
}

/** Mentor personally verifies evidence and signs the action off as completed. */
export function mentorSignOffAction(input: {
  actionId: string;
  mentorName: string;
  note: string;
  impact: string;
}): ActionRecord | undefined {
  const today = "2026-07-17";
  return updateAction(input.actionId, {
    status: "completed",
    evidenceState: "accepted",
    completionEvidence: "Verified against linked evidence pack",
    impact: input.impact,
    progressUpdate: input.note || "Mentor signed off after checking evidence",
    closedDate: today,
    closureReason: "Mentor signed off as completed",
    lastUpdate: today,
    signedOffBy: input.mentorName,
    signedOffAt: today,
    signOffNote: input.note,
    assignedToMe: false,
  });
}

export function toLegacyMentorAction(row: ActionRecord) {
  return {
    actionId: row.actionId,
    title: row.title,
    learnerId: row.learnerId ?? "",
    learnerName: row.learnerName ?? "",
    employerId: row.employerId ?? "",
    employerName: row.employerName ?? "",
    owner: row.owner,
    ownerType: (["apprentice", "employer", "tutor", "provider", "mentor"].includes(
      row.ownerType,
    )
      ? row.ownerType
      : "provider") as "apprentice" | "employer" | "tutor" | "provider" | "mentor",
    sourceType: row.sourceType,
    sourceId: row.sourceId,
    createdAt: row.createdAt,
    dueDate: row.dueDate,
    checkpointDate: row.checkpointDate,
    successMeasure: row.successMeasure,
    evidenceRequirement: row.evidenceRequirement,
    status: (row.status === "escalated"
      ? "escalated"
      : row.status === "overdue"
        ? "overdue"
        : row.status === "awaiting_evidence"
          ? "awaiting_evidence"
          : row.status === "completed" || row.status === "impact_confirmed"
            ? "completed"
            : "open") as
      | "open"
      | "overdue"
      | "awaiting_evidence"
      | "escalated"
      | "completed",
    escalationStatus: row.escalationStatus,
    lastUpdate: row.lastUpdate,
    assignedToMe: row.assignedToMe,
    assignedByMe: row.assignedByMe,
  };
}
