import { ALEX_PROFILE } from "@/features/learner-portal/domain/mock-learner";
import { DEMO_ACCOUNTS } from "@/adapters/fictional/demo-accounts";
import type {
  AdminCohortRecord,
  AdminEmployerRecord,
  AdminLearnerEnrolment,
  AdminLearnerRecord,
  AdminPortalRole,
  AdminPortalUser,
  AdminProgrammeRecord,
  AdminStoreSnapshot,
} from "./types";

const now = "2026-07-25T10:00:00.000Z";

export function createSeedSnapshot(): AdminStoreSnapshot {
  const employers: AdminEmployerRecord[] = [
    {
      id: "emp-riverside",
      name: "Riverside Autocare",
      legalName: "Riverside Autocare Limited",
      companyNumber: "09876543",
      mainContact: "Priya Shah",
      contactRole: "Workplace mentor",
      contactEmail: "priya.shah@riverside-autocare.example",
      contactPhone: "01302 555 210",
      addressLine1: "Unit 4, Riverside Industrial Estate",
      addressLine2: "",
      town: "Doncaster",
      postcode: "DN4 5AB",
      website: "https://riverside-autocare.example",
      status: "active",
      notes: "Primary garage for Alex Morgan and Jordan Blake.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "emp-northline",
      name: "Northline Services Ltd",
      legalName: "Northline Services Limited",
      companyNumber: "07654321",
      mainContact: "James Wilson",
      contactRole: "Employer contact",
      contactEmail: "james.wilson@northline.example",
      contactPhone: "01302 555 220",
      addressLine1: "Northline House",
      addressLine2: "Wheatley Hall Road",
      town: "Doncaster",
      postcode: "DN2 4LT",
      website: "",
      status: "active",
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "emp-donvalley",
      name: "Don Valley Bodyworks",
      legalName: "Don Valley Bodyworks Ltd",
      companyNumber: "11223344",
      mainContact: "Mark Holton",
      contactRole: "Workshop supervisor",
      contactEmail: "mark.holton@donvalley.example",
      contactPhone: "01302 555 230",
      addressLine1: "Don Valley Way",
      addressLine2: "",
      town: "Doncaster",
      postcode: "DN1 3HQ",
      website: "",
      status: "active",
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const programmes: AdminProgrammeRecord[] = [
    {
      id: "prog-autocare-l2",
      name: "Autocare Level 2",
      standardCode: "ST0499",
      level: 2,
      route: "Engineering and manufacturing",
      durationMonths: 30,
      awardingBody: "IMI / City & Guilds",
      status: "active",
      summary:
        "Official title: Autocare Technician. Carries out services and repairs on cars, car-derived vans and light goods vehicles in autocare or fast-fit centres.",
      skillsEnglandUrl:
        "https://skillsengland.education.gov.uk/apprenticeships/st0499-v1-3",
      notes: "Skills England reference ST0499 · Level 2 · typically 30 months.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prog-vmr-l3",
      name: "Vehicle Maintenance and Repair Level 3",
      standardCode: "ST0033",
      level: 3,
      route: "Engineering and manufacturing",
      durationMonths: 36,
      awardingBody: "IMI",
      status: "active",
      summary:
        "Official title: Motor vehicle service and maintenance technician – light vehicle. Servicing, inspecting, diagnosing and repairing light vehicles in dealerships or independent garages.",
      skillsEnglandUrl:
        "https://skillsengland.education.gov.uk/apprenticeships/st0033-v1-5",
      notes: "Skills England reference ST0033 · Level 3 · typically 36 months.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prog-hv-l3",
      name: "Heavy Vehicle Technician Level 3",
      standardCode: "ST0068",
      level: 3,
      route: "Engineering and manufacturing",
      durationMonths: 36,
      awardingBody: "IMI",
      status: "active",
      summary:
        "Official title: Heavy vehicle service and maintenance technician. Services, inspects and repairs heavy vehicles (N2/N3) and associated trailers, including diagnostics and roadside-related competence.",
      skillsEnglandUrl:
        "https://skillsengland.education.gov.uk/apprenticeships/st0068-v1-5",
      notes: "Skills England reference ST0068 · Level 3 · typically 36 months.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prog-paint-l3",
      name: "Vehicle Damage Paint Level 3",
      standardCode: "ST0448",
      level: 3,
      route: "Engineering and manufacturing",
      durationMonths: 36,
      awardingBody: "IMI",
      status: "active",
      summary:
        "Official title: Vehicle damage paint technician. Prepares, sprays and finishes cars and light commercial vehicles after collision or other damage to manufacturer and customer standards.",
      skillsEnglandUrl:
        "https://skillsengland.education.gov.uk/apprenticeships/st0448-v1-2",
      notes: "Skills England reference ST0448 · Level 3 · typically 36 months.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prog-panel-l3",
      name: "Vehicle Damage Panel Level 3",
      standardCode: "ST0403",
      level: 3,
      route: "Engineering and manufacturing",
      durationMonths: 36,
      awardingBody: "IMI",
      status: "active",
      summary:
        "Official title: Vehicle damage panel technician. Removes, repairs and replaces vehicle body panels to manufacturer specification in collision repair workshops.",
      skillsEnglandUrl:
        "https://skillsengland.education.gov.uk/apprenticeships/st0403-v1-3",
      notes: "Skills England reference ST0403 · Level 3 · typically 36 months.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prog-cs-practitioner",
      name: "Customer Service Level 2",
      standardCode: "ST0072",
      level: 2,
      route: "Sales, marketing and procurement",
      durationMonths: 12,
      awardingBody: "IMI / Institute of Customer Service",
      status: "active",
      summary:
        "Official title: Customer service practitioner. Delivers high-quality customer service face-to-face, by phone, digitally or in writing — the entry customer service standard often paired with Specialist.",
      skillsEnglandUrl:
        "https://skillsengland.education.gov.uk/apprenticeships/st0072-v1-1",
      notes:
        "Skills England sets this at Level 2 (not Level 3). Reference ST0072 · typically 12 months.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prog-cs-specialist-l3",
      name: "Customer Service Specialist Level 3",
      standardCode: "ST0071",
      level: 3,
      route: "Sales, marketing and procurement",
      durationMonths: 15,
      awardingBody: "IMI / Institute of Customer Service",
      status: "active",
      summary:
        "Official title: Customer service specialist. Handles complex or escalated customer requests, complaints and queries, and uses insight to improve service.",
      skillsEnglandUrl:
        "https://skillsengland.education.gov.uk/apprenticeships/st0071-v1-3",
      notes: "Skills England reference ST0071 · Level 3 · typically 15 months.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prog-business-admin-l3",
      name: "Business Administration Level 3",
      standardCode: "ST0070",
      level: 3,
      route: "Business and administration",
      durationMonths: 18,
      awardingBody: "Various EPAOs",
      status: "active",
      summary:
        "Official title: Business administrator. Supports and improves administrative services across teams, with strong IT, communication, planning and stakeholder skills.",
      skillsEnglandUrl:
        "https://skillsengland.education.gov.uk/apprenticeships/st0070-v1-0",
      notes: "Skills England reference ST0070 · Level 3 · typically 12–18 months.",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const learners: AdminLearnerRecord[] = [
    {
      id: "lrn-alex-morgan",
      displayName: ALEX_PROFILE.displayName,
      learnerReference: "GTA-2024-01102",
      email: "alex.morgan@example.gta.local",
      phone: "07700 900 111",
      dateOfBirth: "2006-03-14",
      uln: "1234567890",
      addressLine1: "12 Kelham Street",
      addressLine2: "",
      town: "Doncaster",
      postcode: "DN1 3QD",
      emergencyContactName: "Sarah Morgan",
      emergencyContactPhone: "07700 900 411",
      emergencyContactRelationship: "Mother",
      supportNotes: "",
      intakeStatus: "ready",
      // On programme — pre-start pack complete, ongoing OTJ items building up.
      pack: {
        "1.1": "checked",
        "1.2": "checked",
        "1.3": "checked",
        "1.4": "checked",
        "1.5": "checked",
        "1.6": "checked",
        "1.7": "not_applicable",
        "2.1": "checked",
        "2.2": "checked",
        "2.3": "not_applicable",
        "2.4": "checked",
        "3.1": "checked",
        "4.1": "checked",
        "4.2": "checked",
        "5.1": "checked",
        "7.1": "received",
        "7.2": "received",
      },
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lrn-jordan-blake",
      displayName: "Jordan Blake",
      learnerReference: "GTA-2024-01103",
      email: "jordan.blake@example.gta.local",
      phone: "07700 900 112",
      dateOfBirth: "2005-11-02",
      uln: "1234567891",
      addressLine1: "48 Balby Road",
      addressLine2: "",
      town: "Doncaster",
      postcode: "DN4 0RG",
      emergencyContactName: "Chris Blake",
      emergencyContactPhone: "07700 900 412",
      emergencyContactRelationship: "Father",
      supportNotes: "",
      intakeStatus: "ready",
      pack: {
        "1.1": "checked",
        "1.2": "checked",
        "1.3": "checked",
        "1.4": "checked",
        "1.5": "checked",
        "1.6": "checked",
        "1.7": "not_applicable",
        "2.1": "checked",
        "2.2": "checked",
        "2.3": "not_applicable",
        "2.4": "received",
        "3.1": "checked",
        "4.1": "checked",
        "4.2": "checked",
        "5.1": "checked",
        "7.1": "received",
      },
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lrn-sam-reed",
      displayName: "Sam Reed",
      learnerReference: "GTA-2026-01201",
      email: "sam.reed.apprentice@example.gta.local",
      phone: "07700 900 113",
      dateOfBirth: "2007-01-20",
      uln: "1234567892",
      addressLine1: "3 Wheatley Hall Road",
      addressLine2: "",
      town: "Doncaster",
      postcode: "DN2 4LT",
      emergencyContactName: "Joanne Reed",
      emergencyContactPhone: "07700 900 413",
      emergencyContactRelationship: "Mother",
      supportNotes: "",
      intakeStatus: "ready",
      // Pending September start — pre-start pack in, induction happens on day one.
      pack: {
        "1.1": "checked",
        "1.2": "checked",
        "1.3": "checked",
        "1.4": "checked",
        "1.5": "received",
        "1.6": "received",
        "1.7": "not_applicable",
        "2.1": "received",
        "2.2": "received",
        "3.1": "received",
        "4.1": "received",
        "4.2": "received",
      },
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lrn-mia-turner",
      displayName: "Mia Turner",
      learnerReference: "GTA-2026-01207",
      email: "mia.turner@example.gta.local",
      phone: "07700 900 114",
      dateOfBirth: "2008-06-09",
      uln: "1234567893",
      addressLine1: "27 Thorne Road",
      addressLine2: "",
      town: "Doncaster",
      postcode: "DN1 2ES",
      emergencyContactName: "Paul Turner",
      emergencyContactPhone: "07700 900 414",
      emergencyContactRelationship: "Father",
      supportNotes: "",
      intakeStatus: "ready",
      // Ready to start — everything pre-start is in, just needs enrolling.
      pack: {
        "1.1": "checked",
        "1.2": "checked",
        "1.3": "checked",
        "1.4": "checked",
        "1.5": "checked",
        "1.6": "received",
        "1.7": "not_applicable",
        "2.1": "received",
        "2.2": "received",
        "3.1": "received",
        "4.1": "received",
        "4.2": "received",
      },
      notes: "Interested in Vehicle Damage Paint — awaiting employer match.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lrn-ethan-cole",
      displayName: "Ethan Cole",
      learnerReference: "GTA-2026-01212",
      email: "ethan.cole@example.gta.local",
      phone: "",
      dateOfBirth: "2008-02-27",
      uln: "",
      addressLine1: "",
      addressLine2: "",
      town: "Doncaster",
      postcode: "",
      emergencyContactName: "",
      emergencyContactPhone: "",
      emergencyContactRelationship: "",
      supportNotes: "",
      intakeStatus: "in_progress",
      // Application just received — pack barely started.
      pack: {
        "1.2": "received",
      },
      notes: "Application received — chasing missing contact details.",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const enrolments: AdminLearnerEnrolment[] = [
    {
      id: "enr-alex-morgan",
      kind: "currently_studying",
      status: "active",
      learnerId: "lrn-alex-morgan",
      displayName: ALEX_PROFILE.displayName,
      email: "alex.morgan@example.gta.local",
      phone: "07700 900 111",
      dateOfBirth: "2006-03-14",
      uln: "1234567890",
      programmeName: "Autocare Level 2",
      standardCode: "ST0499",
      cohortId: "cohort-autocare-sep-2024",
      employerId: "emp-riverside",
      employerName: "Riverside Autocare",
      workplaceContact: "Priya Shah",
      mentorName: "Priya Shah",
      tutorName: "Sam Reed",
      startDate: "2024-09-02",
      programmeYear: 2,
      programmeWeek: 12,
      attendancePercent: 94,
      actualProgressPercent: 61,
      collegeDays: "Mon, Tue",
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "enr-jordan-blake",
      kind: "currently_studying",
      status: "active",
      learnerId: "lrn-jordan-blake",
      displayName: "Jordan Blake",
      email: "jordan.blake@example.gta.local",
      phone: "07700 900 112",
      dateOfBirth: "2005-11-02",
      uln: "1234567891",
      programmeName: "Autocare Level 2",
      standardCode: "ST0499",
      cohortId: "cohort-autocare-sep-2024",
      employerId: "emp-riverside",
      employerName: "Riverside Autocare",
      workplaceContact: "Priya Shah",
      mentorName: "Priya Shah",
      tutorName: "Sam Reed",
      startDate: "2024-09-02",
      programmeYear: 2,
      programmeWeek: 10,
      attendancePercent: 88,
      actualProgressPercent: 55,
      collegeDays: "Mon, Tue",
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "enr-sam-reed-starter",
      kind: "new_starter",
      status: "pending_start",
      learnerId: "lrn-sam-reed",
      displayName: "Sam Reed",
      email: "sam.reed.apprentice@example.gta.local",
      phone: "07700 900 113",
      dateOfBirth: "2007-01-20",
      uln: "1234567892",
      programmeName: "Autocare Level 2",
      standardCode: "ST0499",
      cohortId: "cohort-autocare-sep-2026",
      employerId: "emp-riverside",
      employerName: "Riverside Autocare",
      workplaceContact: "Priya Shah",
      mentorName: "Priya Shah",
      tutorName: "Sam Reed",
      startDate: "2026-09-07",
      programmeYear: null,
      programmeWeek: null,
      attendancePercent: null,
      actualProgressPercent: null,
      collegeDays: "Mon, Tue",
      notes: "Awaiting start paperwork.",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const cohorts: AdminCohortRecord[] = [
    {
      id: "cohort-autocare-sep-2024",
      name: "Autocare L2 · Sept 2024",
      programmeId: "prog-autocare-l2",
      programmeName: "Autocare Level 2",
      standardCode: "ST0499",
      standardVersion: "1.2",
      enrolmentOpensDate: "2024-03-01",
      startDate: "2024-09-02",
      expectedEndDate: "2027-03-02",
      teachingGroup: "Mon–Tue Group A",
      collegeDays: "Mon, Tue",
      tutorName: "Sam Reed",
      status: "active",
      notes:
        "Started on Skills England v1.2 — finish on this version even if v1.3 is live for new starts.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cohort-autocare-sep-2026",
      name: "Autocare L2 · Sept 2026",
      programmeId: "prog-autocare-l2",
      programmeName: "Autocare Level 2",
      standardCode: "ST0499",
      standardVersion: "1.3",
      enrolmentOpensDate: "2026-03-01",
      startDate: "2026-09-07",
      expectedEndDate: "2029-03-07",
      teachingGroup: "Mon–Tue Group B",
      collegeDays: "Mon, Tue",
      tutorName: "Sam Reed",
      status: "planned",
      notes: "New intake on Skills England v1.3.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cohort-panel-sep-2025",
      name: "Vehicle Damage Panel L3 · Sept 2025",
      programmeId: "prog-panel-l3",
      programmeName: "Vehicle Damage Panel Level 3",
      standardCode: "ST0403",
      standardVersion: "1.3",
      enrolmentOpensDate: "2025-03-01",
      startDate: "2025-09-01",
      expectedEndDate: "2028-09-01",
      teachingGroup: "Wed–Thu Group A",
      collegeDays: "Wed, Thu",
      tutorName: "Sam Reed",
      status: "active",
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const users: AdminPortalUser[] = DEMO_ACCOUNTS.map((account) => ({
    id: `user-${account.id}`,
    displayName: account.name,
    email: account.email,
    role: account.baseRole as AdminPortalRole,
    workspace: account.workspace,
    linkedEnrolmentId:
      account.id === "alex-morgan" ? "enr-alex-morgan" : null,
    linkedEmployerId:
      account.id === "james-wilson" ? "emp-northline" : null,
    status: "active" as const,
    createdAt: now,
    updatedAt: now,
  }));

  return {
    version: 9,
    learners,
    enrolments,
    employers,
    programmes,
    cohorts,
    users,
  };
}
