import { ALEX_PROFILE } from "@/features/learner-portal/domain/mock-learner";
import { DEMO_ACCOUNTS } from "@/adapters/fictional/demo-accounts";
import type {
  AdminEmployerRecord,
  AdminLearnerEnrolment,
  AdminPortalRole,
  AdminPortalUser,
  AdminProgrammeRecord,
  AdminStoreSnapshot,
} from "./types";

const now = "2026-07-25T10:00:00.000Z";

export function createSeedSnapshot(): AdminStoreSnapshot {
  const employers: AdminEmployerRecord[] = [
    {
      id: "emp-riverside",
      name: "Riverside Autocare",
      legalName: "Riverside Autocare Limited",
      companyNumber: "09876543",
      mainContact: "Priya Shah",
      contactRole: "Workplace mentor",
      contactEmail: "priya.shah@riverside-autocare.example",
      contactPhone: "01302 555 210",
      addressLine1: "Unit 4, Riverside Industrial Estate",
      addressLine2: "",
      town: "Doncaster",
      postcode: "DN4 5AB",
      website: "https://riverside-autocare.example",
      status: "active",
      notes: "Primary garage for Alex Morgan and Jordan Blake.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "emp-northline",
      name: "Northline Services Ltd",
      legalName: "Northline Services Limited",
      companyNumber: "07654321",
      mainContact: "James Wilson",
      contactRole: "Employer contact",
      contactEmail: "james.wilson@northline.example",
      contactPhone: "01302 555 220",
      addressLine1: "Northline House",
      addressLine2: "Wheatley Hall Road",
      town: "Doncaster",
      postcode: "DN2 4LT",
      website: "",
      status: "active",
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "emp-donvalley",
      name: "Don Valley Bodyworks",
      legalName: "Don Valley Bodyworks Ltd",
      companyNumber: "11223344",
      mainContact: "Mark Holton",
      contactRole: "Workshop supervisor",
      contactEmail: "mark.holton@donvalley.example",
      contactPhone: "01302 555 230",
      addressLine1: "Don Valley Way",
      addressLine2: "",
      town: "Doncaster",
      postcode: "DN1 3HQ",
      website: "",
      status: "active",
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const programmes: AdminProgrammeRecord[] = [
    {
      id: "prog-autocare-l2",
      name: "Autocare Technician L2",
      standardCode: "ST0499",
      level: 2,
      route: "Engineering and manufacturing",
      durationMonths: 30,
      awardingBody: "IMI / City & Guilds",
      status: "active",
      summary:
        "Services and repairs on cars, car-derived vans and light goods vehicles in autocare or fast-fit centres.",
      skillsEnglandUrl:
        "https://skillsengland.education.gov.uk/apprenticeships/st0499-v1-3",
      notes: "Core GTA automotive starter pathway.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prog-mv-l3",
      name: "Motor Vehicle Service & Maintenance Technician (Light Vehicle) L3",
      standardCode: "ST0033",
      level: 3,
      route: "Engineering and manufacturing",
      durationMonths: 36,
      awardingBody: "IMI",
      status: "active",
      summary:
        "Servicing and repairing light vehicles in dealerships or independent garages, including diagnostics and complex repairs.",
      skillsEnglandUrl:
        "https://skillsengland.education.gov.uk/apprenticeships/st0033-v1-5",
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prog-panel-l3",
      name: "Vehicle Damage Panel Technician L3",
      standardCode: "ST0403",
      level: 3,
      route: "Engineering and manufacturing",
      durationMonths: 36,
      awardingBody: "IMI",
      status: "active",
      summary:
        "Removal, repair and replacement of vehicle body panels to manufacturer specification in collision repair workshops.",
      skillsEnglandUrl:
        "https://skillsengland.education.gov.uk/apprenticeships/st0403-v1-3",
      notes: "Useful for bodyworks employers such as Don Valley.",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const enrolments: AdminLearnerEnrolment[] = [
    {
      id: "enr-alex-morgan",
      kind: "currently_studying",
      status: "active",
      displayName: ALEX_PROFILE.displayName,
      email: "alex.morgan@example.gta.local",
      phone: "07700 900 111",
      dateOfBirth: "2006-03-14",
      uln: "1234567890",
      programmeName: "Autocare Technician L2",
      standardCode: "ST0499",
      employerId: "emp-riverside",
      employerName: "Riverside Autocare",
      workplaceContact: "Priya Shah",
      mentorName: "Priya Shah",
      tutorName: "Sam Reed",
      startDate: "2024-09-02",
      programmeYear: 2,
      programmeWeek: 12,
      attendancePercent: 94,
      actualProgressPercent: 61,
      collegeDays: "Mon, Tue",
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "enr-jordan-blake",
      kind: "currently_studying",
      status: "active",
      displayName: "Jordan Blake",
      email: "jordan.blake@example.gta.local",
      phone: "07700 900 112",
      dateOfBirth: "2005-11-02",
      uln: "1234567891",
      programmeName: "Autocare Technician L2",
      standardCode: "ST0499",
      employerId: "emp-riverside",
      employerName: "Riverside Autocare",
      workplaceContact: "Priya Shah",
      mentorName: "Priya Shah",
      tutorName: "Sam Reed",
      startDate: "2024-09-02",
      programmeYear: 2,
      programmeWeek: 10,
      attendancePercent: 88,
      actualProgressPercent: 55,
      collegeDays: "Mon, Tue",
      notes: "",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "enr-sam-reed-starter",
      kind: "new_starter",
      status: "pending_start",
      displayName: "Sam Reed",
      email: "sam.reed.apprentice@example.gta.local",
      phone: "07700 900 113",
      dateOfBirth: "2007-01-20",
      uln: "",
      programmeName: "Autocare Technician L2",
      standardCode: "ST0499",
      employerId: "emp-riverside",
      employerName: "Riverside Autocare",
      workplaceContact: "Priya Shah",
      mentorName: "Priya Shah",
      tutorName: "Sam Reed",
      startDate: "2026-09-07",
      programmeYear: null,
      programmeWeek: null,
      attendancePercent: null,
      actualProgressPercent: null,
      collegeDays: "Mon, Tue",
      notes: "Awaiting start paperwork.",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const users: AdminPortalUser[] = DEMO_ACCOUNTS.map((account) => ({
    id: `user-${account.id}`,
    displayName: account.name,
    email: account.email,
    role: account.baseRole as AdminPortalRole,
    workspace: account.workspace,
    linkedEnrolmentId:
      account.id === "alex-morgan" ? "enr-alex-morgan" : null,
    linkedEmployerId:
      account.id === "james-wilson" ? "emp-northline" : null,
    status: "active" as const,
    createdAt: now,
    updatedAt: now,
  }));

  return { version: 3, enrolments, employers, programmes, users };
}
